// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespace}\activities\{activityId}\outcome
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OutcomeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OutcomeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/activities/{activityId}/outcome{?runId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OutcomeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/activities/{activityId}/outcome{?runId*}", rawUrl)
        {
        }
        /// <summary>
        /// PollActivityExecution long-polls for an activity execution to complete and returns the outcome (result or failure).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.PollActivityExecutionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Temporal.OpenApiClient.Models.Status">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.PollActivityExecutionResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder.OutcomeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.PollActivityExecutionResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder.OutcomeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Temporal.OpenApiClient.Models.Status.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Temporal.OpenApiClient.Models.PollActivityExecutionResponse>(requestInfo, global::Soenneker.Temporal.OpenApiClient.Models.PollActivityExecutionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// PollActivityExecution long-polls for an activity execution to complete and returns the outcome (result or failure).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder.OutcomeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder.OutcomeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Activities.Item.Outcome.OutcomeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// PollActivityExecution long-polls for an activity execution to complete and returns the outcome (result or failure).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OutcomeRequestBuilderGetQueryParameters 
        {
            /// <summary>Activity run ID. If empty the request targets the latest run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("runId")]
            public string? RunId { get; set; }
#nullable restore
#else
            [QueryParameter("runId")]
            public string RunId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
