// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespace}\workflows\{executionWorkflow_-id}\signal-with-start
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignalWithStartRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Temporal.OpenApiClient.namespaces.item.workflows.item.signalWithStart.item collection</summary>
        /// <param name="position">The workflow author-defined name of the signal to send to the workflow</param>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.Item.WithSignalNameItemRequestBuilder"/></returns>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.Item.WithSignalNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("signalName", position);
                return new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.Item.WithSignalNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.SignalWithStartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SignalWithStartRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workflows/{executionWorkflow_%2Did}/signal-with-start", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.SignalWithStart.SignalWithStartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SignalWithStartRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workflows/{executionWorkflow_%2Did}/signal-with-start", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
