// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\namespaces\{namespace}\activity-heartbeat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityHeartbeatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat.ActivityHeartbeatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityHeartbeatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/namespaces/{namespace}/activity-heartbeat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat.ActivityHeartbeatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityHeartbeatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/namespaces/{namespace}/activity-heartbeat", rawUrl)
        {
        }
        /// <summary>
        /// RecordActivityTaskHeartbeat is optionally called by workers while they execute activities. If a worker fails to heartbeat within the `heartbeat_timeout` interval for the activity task, then the current attempt times out. Depending on RetryPolicy, this may trigger a retry or time out the activity. For workflow activities, an `ACTIVITY_TASK_TIMED_OUT` event will be written to the workflow history. Calling `RecordActivityTaskHeartbeat` will fail with `NotFound` in such situations, in that event, the SDK should request cancellation of the activity. The request may contain response `details` which will be persisted by the server and may be used by the activity to checkpoint progress. The `cancel_requested` field in the response indicates whether cancellation has been requested for the activity.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Temporal.OpenApiClient.Models.Status">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse?> PostAsync(global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse> PostAsync(global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Temporal.OpenApiClient.Models.Status.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse>(requestInfo, global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// RecordActivityTaskHeartbeat is optionally called by workers while they execute activities. If a worker fails to heartbeat within the `heartbeat_timeout` interval for the activity task, then the current attempt times out. Depending on RetryPolicy, this may trigger a retry or time out the activity. For workflow activities, an `ACTIVITY_TASK_TIMED_OUT` event will be written to the workflow history. Calling `RecordActivityTaskHeartbeat` will fail with `NotFound` in such situations, in that event, the SDK should request cancellation of the activity. The request may contain response `details` which will be persisted by the server and may be used by the activity to checkpoint progress. The `cancel_requested` field in the response indicates whether cancellation has been requested for the activity.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat.ActivityHeartbeatRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat.ActivityHeartbeatRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.ActivityHeartbeat.ActivityHeartbeatRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
