// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Models;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Describe;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.FetchConfig;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Heartbeat;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.UpdateConfig;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespace}\workers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The describe property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Describe.DescribeRequestBuilder Describe
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Describe.DescribeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fetchConfig property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.FetchConfig.FetchConfigRequestBuilder FetchConfig
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.FetchConfig.FetchConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heartbeat property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Heartbeat.HeartbeatRequestBuilder Heartbeat
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.Heartbeat.HeartbeatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateConfig property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.UpdateConfig.UpdateConfigRequestBuilder UpdateConfig
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.UpdateConfig.UpdateConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workers{?nextPageToken*,pageSize*,query*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workers{?nextPageToken*,pageSize*,query*}", rawUrl)
        {
        }
        /// <summary>
        /// ListWorkers is a visibility API to list worker status information in a specific namespace.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.ListWorkersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Temporal.OpenApiClient.Models.Status">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.ListWorkersResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder.WorkersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.ListWorkersResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder.WorkersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Temporal.OpenApiClient.Models.Status.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Temporal.OpenApiClient.Models.ListWorkersResponse>(requestInfo, global::Soenneker.Temporal.OpenApiClient.Models.ListWorkersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ListWorkers is a visibility API to list worker status information in a specific namespace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder.WorkersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder.WorkersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workers.WorkersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// ListWorkers is a visibility API to list worker status information in a specific namespace.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkersRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nextPageToken")]
            public string? NextPageToken { get; set; }
#nullable restore
#else
            [QueryParameter("nextPageToken")]
            public string NextPageToken { get; set; }
#endif
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
            /// <summary>`query` in ListWorkers is used to filter workers based on worker attributes. Supported attributes:* WorkerInstanceKey* WorkerIdentity* HostName* TaskQueue* DeploymentName* BuildId* SdkName* SdkVersion* StartTime* Status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
