// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespace}\workflows\{executionWorkflow_-id}\activities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Temporal.OpenApiClient.namespaces.item.workflows.item.activities.item collection</summary>
        /// <param name="position">Id of the activity to complete</param>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.Item.WithActivityItemRequestBuilder"/></returns>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.Item.WithActivityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("activityId", position);
                return new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.Item.WithActivityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workflows/{executionWorkflow_%2Did}/activities", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Workflows.Item.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/workflows/{executionWorkflow_%2Did}/activities", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
