// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\namespaces\{namespace}\nexus-operations\{operationId}\poll
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PollRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/namespaces/{namespace}/nexus-operations/{operationId}/poll{?runId*,waitStage*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/namespaces/{namespace}/nexus-operations/{operationId}/poll{?runId*,waitStage*}", rawUrl)
        {
        }
        /// <summary>
        /// PollNexusOperationExecution long-polls for a Nexus operation for a given wait stage to complete and returns the outcome (result or failure).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.PollNexusOperationExecutionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Temporal.OpenApiClient.Models.Status">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.PollNexusOperationExecutionResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder.PollRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Temporal.OpenApiClient.Models.PollNexusOperationExecutionResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder.PollRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Temporal.OpenApiClient.Models.Status.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Temporal.OpenApiClient.Models.PollNexusOperationExecutionResponse>(requestInfo, global::Soenneker.Temporal.OpenApiClient.Models.PollNexusOperationExecutionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// PollNexusOperationExecution long-polls for a Nexus operation for a given wait stage to complete and returns the outcome (result or failure).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder.PollRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder.PollRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.PollRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// PollNexusOperationExecution long-polls for a Nexus operation for a given wait stage to complete and returns the outcome (result or failure).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PollRequestBuilderGetQueryParameters 
        {
            /// <summary>Operation run ID. If empty the request targets the latest run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("runId")]
            public string? RunId { get; set; }
#nullable restore
#else
            [QueryParameter("runId")]
            public string RunId { get; set; }
#endif
            /// <summary>Stage to wait for. The operation may be in a more advanced stage when the poll is unblocked.</summary>
            [QueryParameter("waitStage")]
            public global::Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.NexusOperations.Item.Poll.GetWaitStageQueryParameterType? WaitStage { get; set; }
        }
    }
}
#pragma warning restore CS0618
