// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespaceValue}\deployments\{deploymentSeriesName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeploymentSeriesNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Temporal.OpenApiClient.namespaces.item.deployments.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.Item.WithDeploymentBuildItemRequestBuilder"/></returns>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.Item.WithDeploymentBuildItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deploymentBuildId", position);
                return new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.Item.WithDeploymentBuildItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.WithDeploymentSeriesNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeploymentSeriesNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespaceValue}/deployments/{deploymentSeriesName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.Deployments.Item.WithDeploymentSeriesNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeploymentSeriesNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespaceValue}/deployments/{deploymentSeriesName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
