// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Only scheduled and terminal statuses appear here. More detailed information in PendingActivityInfo but not available in the list response.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActivityExecutionListInfo_status
    {
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_RUNNING")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_RUNNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_COMPLETED")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_FAILED")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_CANCELED")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_CANCELED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_TERMINATED")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_TERMINATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVITY_EXECUTION_STATUS_TIMED_OUT")]
        #pragma warning disable CS1591
        ACTIVITY_EXECUTION_STATUS_TIMED_OUT,
        #pragma warning restore CS1591
    }
}
