// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Alert_severity
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SEVERITY_UNSPECIFIED")]
        #pragma warning disable CS1591
        SEVERITY_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEVERITY_HIGH")]
        #pragma warning disable CS1591
        SEVERITY_HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEVERITY_MEDIUM")]
        #pragma warning disable CS1591
        SEVERITY_MEDIUM,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEVERITY_LOW")]
        #pragma warning disable CS1591
        SEVERITY_LOW,
        #pragma warning restore CS1591
    }
}
