// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>If set, override overlap policy for this request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BackfillRequestOverlapPolicy
    {
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_UNSPECIFIED")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_SKIP")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicySkip,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_BUFFER_ONE")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyBufferOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_BUFFER_ALL")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyBufferAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyCancelOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyTerminateOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCHEDULE_OVERLAP_POLICY_ALLOW_ALL")]
        #pragma warning disable CS1591
        ScheduleOverlapPolicyAllowAll,
        #pragma warning restore CS1591
    }
}
