// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Deprecated. Use `options`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchOperationResetResetType
    {
        [EnumMember(Value = "RESET_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        ResetTypeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESET_TYPE_FIRST_WORKFLOW_TASK")]
        #pragma warning disable CS1591
        ResetTypeFirstWorkflowTask,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESET_TYPE_LAST_WORKFLOW_TASK")]
        #pragma warning disable CS1591
        ResetTypeLastWorkflowTask,
        #pragma warning restore CS1591
    }
}
