// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// BatchOperationUnpauseActivities sends unpause requests to batch workflows.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchOperationUnpauseActivities : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The identity of the worker/client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>If set, the activity will start at a random time within the specified jitter duration, introducing variability to the start time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Jitter { get; set; }
#nullable restore
#else
        public string Jitter { get; set; }
#endif
        /// <summary>The matchAll property</summary>
        public bool? MatchAll { get; set; }
        /// <summary>Setting this flag will also reset the number of attempts.</summary>
        public bool? ResetAttempts { get; set; }
        /// <summary>Setting this flag will also reset the heartbeat details.</summary>
        public bool? ResetHeartbeat { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.BatchOperationUnpauseActivities"/> and sets the default values.
        /// </summary>
        public BatchOperationUnpauseActivities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.BatchOperationUnpauseActivities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.BatchOperationUnpauseActivities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.BatchOperationUnpauseActivities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "jitter", n => { Jitter = n.GetStringValue(); } },
                { "matchAll", n => { MatchAll = n.GetBoolValue(); } },
                { "resetAttempts", n => { ResetAttempts = n.GetBoolValue(); } },
                { "resetHeartbeat", n => { ResetHeartbeat = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("identity", Identity);
            writer.WriteStringValue("jitter", Jitter);
            writer.WriteBoolValue("matchAll", MatchAll);
            writer.WriteBoolValue("resetAttempts", ResetAttempts);
            writer.WriteBoolValue("resetHeartbeat", ResetHeartbeat);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
