// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>The current state of the callback.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CallbackInfoState
    {
        [EnumMember(Value = "CALLBACK_STATE_UNSPECIFIED")]
        #pragma warning disable CS1591
        CallbackStateUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_STANDBY")]
        #pragma warning disable CS1591
        CallbackStateStandby,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_SCHEDULED")]
        #pragma warning disable CS1591
        CallbackStateScheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_BACKING_OFF")]
        #pragma warning disable CS1591
        CallbackStateBackingOff,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_FAILED")]
        #pragma warning disable CS1591
        CallbackStateFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_SUCCEEDED")]
        #pragma warning disable CS1591
        CallbackStateSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "CALLBACK_STATE_BLOCKED")]
        #pragma warning disable CS1591
        CallbackStateBlocked,
        #pragma warning restore CS1591
    }
}
