// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DataBlobEncodingType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ENCODING_TYPE_UNSPECIFIED")]
        #pragma warning disable CS1591
        EncodingTypeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENCODING_TYPE_PROTO3")]
        #pragma warning disable CS1591
        EncodingTypeProto3,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENCODING_TYPE_JSON")]
        #pragma warning disable CS1591
        EncodingTypeJson,
        #pragma warning restore CS1591
    }
}
