// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DescribeWorkerDeploymentVersionResponse_VersionTaskQueue : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Only set if `report_task_queue_stats` is set on the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats? Stats { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats Stats { get; set; }
#endif
        /// <summary>Task queue stats breakdown by priority key. Only contains actively used priority keys. Only set if `report_task_queue_stats` is set to true in the request. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &quot;by&quot; is used to clarify the key. --)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_statsByPriorityKey? StatsByPriorityKey { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_statsByPriorityKey StatsByPriorityKey { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue"/> and sets the default values.
        /// </summary>
        public DescribeWorkerDeploymentVersionResponse_VersionTaskQueue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "stats", n => { Stats = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats.CreateFromDiscriminatorValue); } },
                { "statsByPriorityKey", n => { StatsByPriorityKey = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_statsByPriorityKey>(global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_statsByPriorityKey.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats>("stats", Stats);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_statsByPriorityKey>("statsByPriorityKey", StatsByPriorityKey);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeWorkerDeploymentVersionResponse_VersionTaskQueue_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
