// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DescribeTaskQueueResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Only populated if report_task_queue_config is set to true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueConfig Config { get; set; }
#endif
        /// <summary>The effectiveRateLimit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_EffectiveRateLimit? EffectiveRateLimit { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_EffectiveRateLimit EffectiveRateLimit { get; set; }
#endif
        /// <summary>The pollers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Temporal.OpenApiClient.Models.PollerInfo>? Pollers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Temporal.OpenApiClient.Models.PollerInfo> Pollers { get; set; }
#endif
        /// <summary>Statistics for the task queue. Only set if `report_stats` is set on the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats? Stats { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats Stats { get; set; }
#endif
        /// <summary>Task queue stats breakdown by priority key. Only contains actively used priority keys. Only set if `report_stats` is set on the request. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &quot;by&quot; is used to clarify the keys and values. --)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_statsByPriorityKey? StatsByPriorityKey { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_statsByPriorityKey StatsByPriorityKey { get; set; }
#endif
        /// <summary>Deprecated. Status of the task queue. Only populated when `include_task_queue_status` is set to true in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStatus? TaskQueueStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStatus TaskQueueStatus { get; set; }
#endif
        /// <summary>Specifies which Worker Deployment Version(s) Server routes this Task Queue&apos;s tasks to. When not present, it means the tasks are routed to Unversioned workers (workers with UNVERSIONED or unspecified WorkerVersioningMode.) Task Queue Versioning info is updated indirectly by calling SetWorkerDeploymentCurrentVersion and SetWorkerDeploymentRampingVersion on Worker Deployments. Note: This information is not relevant to Pinned workflow executions and their activities as they are always routed to their Pinned Deployment Version. However, new workflow executions are typically not Pinned until they complete their first task (unless they are started with a Pinned VersioningOverride or are Child Workflows of a Pinned parent).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueVersioningInfo? VersioningInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueVersioningInfo VersioningInfo { get; set; }
#endif
        /// <summary>Deprecated. Only returned in ENHANCED mode. This map contains Task Queue information for each Build ID. Empty string as key value means unversioned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_versionsInfo? VersionsInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_versionsInfo VersionsInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse"/> and sets the default values.
        /// </summary>
        public DescribeTaskQueueResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueConfig>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueConfig.CreateFromDiscriminatorValue); } },
                { "effectiveRateLimit", n => { EffectiveRateLimit = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_EffectiveRateLimit>(global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_EffectiveRateLimit.CreateFromDiscriminatorValue); } },
                { "pollers", n => { Pollers = n.GetCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.PollerInfo>(global::Soenneker.Temporal.OpenApiClient.Models.PollerInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stats", n => { Stats = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats.CreateFromDiscriminatorValue); } },
                { "statsByPriorityKey", n => { StatsByPriorityKey = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_statsByPriorityKey>(global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_statsByPriorityKey.CreateFromDiscriminatorValue); } },
                { "taskQueueStatus", n => { TaskQueueStatus = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStatus>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStatus.CreateFromDiscriminatorValue); } },
                { "versioningInfo", n => { VersioningInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueVersioningInfo>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueVersioningInfo.CreateFromDiscriminatorValue); } },
                { "versionsInfo", n => { VersionsInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_versionsInfo>(global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_versionsInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueConfig>("config", Config);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_EffectiveRateLimit>("effectiveRateLimit", EffectiveRateLimit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.PollerInfo>("pollers", Pollers);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStats>("stats", Stats);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_statsByPriorityKey>("statsByPriorityKey", StatsByPriorityKey);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueStatus>("taskQueueStatus", TaskQueueStatus);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueueVersioningInfo>("versioningInfo", VersioningInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.DescribeTaskQueueResponse_versionsInfo>("versionsInfo", VersionsInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
