// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DescribeTaskQueue2TaskQueueKindParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TASK_QUEUE_KIND_UNSPECIFIED")]
        #pragma warning disable CS1591
        TaskQueueKindUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_QUEUE_KIND_NORMAL")]
        #pragma warning disable CS1591
        TaskQueueKindNormal,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_QUEUE_KIND_STICKY")]
        #pragma warning disable CS1591
        TaskQueueKindSticky,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_QUEUE_KIND_WORKER_COMMANDS")]
        #pragma warning disable CS1591
        TaskQueueKindWorkerCommands,
        #pragma warning restore CS1591
    }
}
