// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Failure : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activityFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityFailureInfo? ActivityFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityFailureInfo ActivityFailureInfo { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The applicationFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ApplicationFailureInfo? ApplicationFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ApplicationFailureInfo ApplicationFailureInfo { get; set; }
#endif
        /// <summary>The canceledFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.CanceledFailureInfo? CanceledFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.CanceledFailureInfo CanceledFailureInfo { get; set; }
#endif
        /// <summary>The cause property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure? Cause { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure Cause { get; set; }
#endif
        /// <summary>The childWorkflowExecutionFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailureInfo? ChildWorkflowExecutionFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailureInfo ChildWorkflowExecutionFailureInfo { get; set; }
#endif
        /// <summary>Alternative way to supply `message` and `stack_trace` and possibly other attributes, used for encryption of errors originating in user code which might contain sensitive information. The `encoded_attributes` Payload could represent any serializable object, e.g. JSON object or a `Failure` proto message. SDK authors: - The SDK should provide a default `encodeFailureAttributes` and `decodeFailureAttributes` implementation that:   - Uses a JSON object to represent `{ message, stack_trace }`.   - Overwrites the original message with &quot;Encoded failure&quot; to indicate that more information could be extracted.   - Overwrites the original stack_trace with an empty string.   - The resulting JSON object is converted to Payload using the default PayloadConverter and should be processed     by the user-provided PayloadCodec - If there&apos;s demand, we could allow overriding the default SDK implementation to encode other opaque Failure attributes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? EncodedAttributes { get; set; }
#nullable restore
#else
        public UntypedNode EncodedAttributes { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The nexusHandlerFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusHandlerFailureInfo? NexusHandlerFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusHandlerFailureInfo NexusHandlerFailureInfo { get; set; }
#endif
        /// <summary>Representation of the Temporal SDK NexusOperationError object that is returned to workflow callers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailureInfo? NexusOperationExecutionFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailureInfo NexusOperationExecutionFailureInfo { get; set; }
#endif
        /// <summary>The resetWorkflowFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ResetWorkflowFailureInfo? ResetWorkflowFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ResetWorkflowFailureInfo ResetWorkflowFailureInfo { get; set; }
#endif
        /// <summary>The serverFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ServerFailureInfo? ServerFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ServerFailureInfo ServerFailureInfo { get; set; }
#endif
        /// <summary>The source this Failure originated in, e.g. TypeScriptSDK / JavaSDK In some SDKs this is used to rehydrate the stack trace into an exception object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The stackTrace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StackTrace { get; set; }
#nullable restore
#else
        public string StackTrace { get; set; }
#endif
        /// <summary>The terminatedFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TerminatedFailureInfo? TerminatedFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TerminatedFailureInfo TerminatedFailureInfo { get; set; }
#endif
        /// <summary>The timeoutFailureInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TimeoutFailureInfo? TimeoutFailureInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TimeoutFailureInfo TimeoutFailureInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.Failure"/> and sets the default values.
        /// </summary>
        public Failure()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.Failure"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.Failure CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.Failure();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activityFailureInfo", n => { ActivityFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityFailureInfo.CreateFromDiscriminatorValue); } },
                { "applicationFailureInfo", n => { ApplicationFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ApplicationFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.ApplicationFailureInfo.CreateFromDiscriminatorValue); } },
                { "canceledFailureInfo", n => { CanceledFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.CanceledFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.CanceledFailureInfo.CreateFromDiscriminatorValue); } },
                { "cause", n => { Cause = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>(global::Soenneker.Temporal.OpenApiClient.Models.Failure.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionFailureInfo", n => { ChildWorkflowExecutionFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailureInfo.CreateFromDiscriminatorValue); } },
                { "encodedAttributes", n => { EncodedAttributes = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "nexusHandlerFailureInfo", n => { NexusHandlerFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusHandlerFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.NexusHandlerFailureInfo.CreateFromDiscriminatorValue); } },
                { "nexusOperationExecutionFailureInfo", n => { NexusOperationExecutionFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailureInfo.CreateFromDiscriminatorValue); } },
                { "resetWorkflowFailureInfo", n => { ResetWorkflowFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ResetWorkflowFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.ResetWorkflowFailureInfo.CreateFromDiscriminatorValue); } },
                { "serverFailureInfo", n => { ServerFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ServerFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.ServerFailureInfo.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "stackTrace", n => { StackTrace = n.GetStringValue(); } },
                { "terminatedFailureInfo", n => { TerminatedFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TerminatedFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.TerminatedFailureInfo.CreateFromDiscriminatorValue); } },
                { "timeoutFailureInfo", n => { TimeoutFailureInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimeoutFailureInfo>(global::Soenneker.Temporal.OpenApiClient.Models.TimeoutFailureInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityFailureInfo>("activityFailureInfo", ActivityFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ApplicationFailureInfo>("applicationFailureInfo", ApplicationFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.CanceledFailureInfo>("canceledFailureInfo", CanceledFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>("cause", Cause);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailureInfo>("childWorkflowExecutionFailureInfo", ChildWorkflowExecutionFailureInfo);
            writer.WriteObjectValue<UntypedNode>("encodedAttributes", EncodedAttributes);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusHandlerFailureInfo>("nexusHandlerFailureInfo", NexusHandlerFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailureInfo>("nexusOperationExecutionFailureInfo", NexusOperationExecutionFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ResetWorkflowFailureInfo>("resetWorkflowFailureInfo", ResetWorkflowFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ServerFailureInfo>("serverFailureInfo", ServerFailureInfo);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("stackTrace", StackTrace);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TerminatedFailureInfo>("terminatedFailureInfo", TerminatedFailureInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimeoutFailureInfo>("timeoutFailureInfo", TimeoutFailureInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
