// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetDeploymentReachabilityResponseReachability
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DEPLOYMENT_REACHABILITY_UNSPECIFIED")]
        #pragma warning disable CS1591
        DeploymentReachabilityUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_REACHABILITY_REACHABLE")]
        #pragma warning disable CS1591
        DeploymentReachabilityReachable,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_REACHABILITY_CLOSED_WORKFLOWS_ONLY")]
        #pragma warning disable CS1591
        DeploymentReachabilityClosedWorkflowsOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPLOYMENT_REACHABILITY_UNREACHABLE")]
        #pragma warning disable CS1591
        DeploymentReachabilityUnreachable,
        #pragma warning restore CS1591
    }
}
