// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// History events are the method by which Temporal SDKs advance (or recreate) workflow state. See the `EventType` enum for more info about what each event is for.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HistoryEvent : IAdditionalDataHolder, IParsable
    {
        /// <summary>The activityPropertiesModifiedExternallyEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityPropertiesModifiedExternallyEventAttributes? ActivityPropertiesModifiedExternallyEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityPropertiesModifiedExternallyEventAttributes ActivityPropertiesModifiedExternallyEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskCanceledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCanceledEventAttributes? ActivityTaskCanceledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCanceledEventAttributes ActivityTaskCanceledEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskCancelRequestedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCancelRequestedEventAttributes? ActivityTaskCancelRequestedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCancelRequestedEventAttributes ActivityTaskCancelRequestedEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCompletedEventAttributes? ActivityTaskCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCompletedEventAttributes ActivityTaskCompletedEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskFailedEventAttributes? ActivityTaskFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskFailedEventAttributes ActivityTaskFailedEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskScheduledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskScheduledEventAttributes? ActivityTaskScheduledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskScheduledEventAttributes ActivityTaskScheduledEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskStartedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskStartedEventAttributes? ActivityTaskStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskStartedEventAttributes ActivityTaskStartedEventAttributes { get; set; }
#endif
        /// <summary>The activityTaskTimedOutEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskTimedOutEventAttributes? ActivityTaskTimedOutEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskTimedOutEventAttributes ActivityTaskTimedOutEventAttributes { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The childWorkflowExecutionCanceledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCanceledEventAttributes? ChildWorkflowExecutionCanceledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCanceledEventAttributes ChildWorkflowExecutionCanceledEventAttributes { get; set; }
#endif
        /// <summary>The childWorkflowExecutionCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCompletedEventAttributes? ChildWorkflowExecutionCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCompletedEventAttributes ChildWorkflowExecutionCompletedEventAttributes { get; set; }
#endif
        /// <summary>The childWorkflowExecutionFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailedEventAttributes? ChildWorkflowExecutionFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailedEventAttributes ChildWorkflowExecutionFailedEventAttributes { get; set; }
#endif
        /// <summary>The childWorkflowExecutionStartedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionStartedEventAttributes? ChildWorkflowExecutionStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionStartedEventAttributes ChildWorkflowExecutionStartedEventAttributes { get; set; }
#endif
        /// <summary>The childWorkflowExecutionTerminatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTerminatedEventAttributes? ChildWorkflowExecutionTerminatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTerminatedEventAttributes ChildWorkflowExecutionTerminatedEventAttributes { get; set; }
#endif
        /// <summary>The childWorkflowExecutionTimedOutEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTimedOutEventAttributes? ChildWorkflowExecutionTimedOutEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTimedOutEventAttributes ChildWorkflowExecutionTimedOutEventAttributes { get; set; }
#endif
        /// <summary>Monotonically increasing event number, starts at 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventId { get; set; }
#nullable restore
#else
        public string EventId { get; set; }
#endif
        /// <summary>The eventTime property</summary>
        public DateTimeOffset? EventTime { get; set; }
        /// <summary>The eventType property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent_eventType? EventType { get; set; }
        /// <summary>The externalWorkflowExecutionCancelRequestedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionCancelRequestedEventAttributes? ExternalWorkflowExecutionCancelRequestedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionCancelRequestedEventAttributes ExternalWorkflowExecutionCancelRequestedEventAttributes { get; set; }
#endif
        /// <summary>The externalWorkflowExecutionSignaledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionSignaledEventAttributes? ExternalWorkflowExecutionSignaledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionSignaledEventAttributes ExternalWorkflowExecutionSignaledEventAttributes { get; set; }
#endif
        /// <summary>Links to related entities, such as the entity that started this event&apos;s workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link> Links { get; set; }
#endif
        /// <summary>The markerRecordedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.MarkerRecordedEventAttributes? MarkerRecordedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.MarkerRecordedEventAttributes MarkerRecordedEventAttributes { get; set; }
#endif
        /// <summary>Nexus operation completed as canceled. May or may not have been due to a cancellation request by the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCanceledEventAttributes? NexusOperationCanceledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCanceledEventAttributes NexusOperationCanceledEventAttributes { get; set; }
#endif
        /// <summary>The nexusOperationCancelRequestCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestCompletedEventAttributes? NexusOperationCancelRequestCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestCompletedEventAttributes NexusOperationCancelRequestCompletedEventAttributes { get; set; }
#endif
        /// <summary>The nexusOperationCancelRequestedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestedEventAttributes? NexusOperationCancelRequestedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestedEventAttributes NexusOperationCancelRequestedEventAttributes { get; set; }
#endif
        /// <summary>The nexusOperationCancelRequestFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestFailedEventAttributes? NexusOperationCancelRequestFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestFailedEventAttributes NexusOperationCancelRequestFailedEventAttributes { get; set; }
#endif
        /// <summary>Nexus operation completed successfully.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCompletedEventAttributes? NexusOperationCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCompletedEventAttributes NexusOperationCompletedEventAttributes { get; set; }
#endif
        /// <summary>Nexus operation failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailedEventAttributes? NexusOperationFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailedEventAttributes NexusOperationFailedEventAttributes { get; set; }
#endif
        /// <summary>Event marking that an operation was scheduled by a workflow via the ScheduleNexusOperation command.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationScheduledEventAttributes? NexusOperationScheduledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationScheduledEventAttributes NexusOperationScheduledEventAttributes { get; set; }
#endif
        /// <summary>Event marking an asynchronous operation was started by the responding Nexus handler. If the operation completes synchronously, this event is not generated. In rare situations, such as request timeouts, the service may fail to record the actual start time and will fabricate this event upon receiving the operation completion via callback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationStartedEventAttributes? NexusOperationStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationStartedEventAttributes NexusOperationStartedEventAttributes { get; set; }
#endif
        /// <summary>Nexus operation timed out.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationTimedOutEventAttributes? NexusOperationTimedOutEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationTimedOutEventAttributes NexusOperationTimedOutEventAttributes { get; set; }
#endif
        /// <summary>Server-computed authenticated caller identity associated with this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Principal? Principal { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Principal Principal { get; set; }
#endif
        /// <summary>The requestCancelExternalWorkflowExecutionFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionFailedEventAttributes? RequestCancelExternalWorkflowExecutionFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionFailedEventAttributes RequestCancelExternalWorkflowExecutionFailedEventAttributes { get; set; }
#endif
        /// <summary>The requestCancelExternalWorkflowExecutionInitiatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionInitiatedEventAttributes? RequestCancelExternalWorkflowExecutionInitiatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionInitiatedEventAttributes RequestCancelExternalWorkflowExecutionInitiatedEventAttributes { get; set; }
#endif
        /// <summary>The signalExternalWorkflowExecutionFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionFailedEventAttributes? SignalExternalWorkflowExecutionFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionFailedEventAttributes SignalExternalWorkflowExecutionFailedEventAttributes { get; set; }
#endif
        /// <summary>The signalExternalWorkflowExecutionInitiatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionInitiatedEventAttributes? SignalExternalWorkflowExecutionInitiatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionInitiatedEventAttributes SignalExternalWorkflowExecutionInitiatedEventAttributes { get; set; }
#endif
        /// <summary>The startChildWorkflowExecutionFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionFailedEventAttributes? StartChildWorkflowExecutionFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionFailedEventAttributes StartChildWorkflowExecutionFailedEventAttributes { get; set; }
#endif
        /// <summary>The startChildWorkflowExecutionInitiatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionInitiatedEventAttributes? StartChildWorkflowExecutionInitiatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionInitiatedEventAttributes StartChildWorkflowExecutionInitiatedEventAttributes { get; set; }
#endif
        /// <summary>Identifier used by the service to order replication and transfer tasks associated with this event. SDKs generally ignore this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskId { get; set; }
#nullable restore
#else
        public string TaskId { get; set; }
#endif
        /// <summary>The timerCanceledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerCanceledEventAttributes? TimerCanceledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerCanceledEventAttributes TimerCanceledEventAttributes { get; set; }
#endif
        /// <summary>The timerFiredEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerFiredEventAttributes? TimerFiredEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerFiredEventAttributes TimerFiredEventAttributes { get; set; }
#endif
        /// <summary>The timerStartedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerStartedEventAttributes? TimerStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TimerStartedEventAttributes TimerStartedEventAttributes { get; set; }
#endif
        /// <summary>The upsertWorkflowSearchAttributesEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.UpsertWorkflowSearchAttributesEventAttributes? UpsertWorkflowSearchAttributesEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.UpsertWorkflowSearchAttributesEventAttributes UpsertWorkflowSearchAttributesEventAttributes { get; set; }
#endif
        /// <summary>Metadata on the event. This is often carried over from commands and client calls. Most events won&apos;t have this information, and how this information is used is dependent upon the interface that reads it. Current well-known uses:  * workflow_execution_started_event_attributes - summary and details from start workflow.  * timer_started_event_attributes - summary represents an identifier for the timer for use by    user interfaces.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata? UserMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata UserMetadata { get; set; }
#endif
        /// <summary>Failover version of the event, used by the server for multi-cluster replication and history versioning. SDKs generally ignore this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>Set to true when the SDK may ignore the event as it does not impact workflow state or information in any way that the SDK need be concerned with. If an SDK encounters an event type which it does not understand, it must error unless this is true. If it is true, it&apos;s acceptable for the event type and/or attributes to be uninterpretable.</summary>
        public bool? WorkerMayIgnore { get; set; }
        /// <summary>The workflowExecutionCanceledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCanceledEventAttributes? WorkflowExecutionCanceledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCanceledEventAttributes WorkflowExecutionCanceledEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionCancelRequestedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCancelRequestedEventAttributes? WorkflowExecutionCancelRequestedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCancelRequestedEventAttributes WorkflowExecutionCancelRequestedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCompletedEventAttributes? WorkflowExecutionCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCompletedEventAttributes WorkflowExecutionCompletedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionContinuedAsNewEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionContinuedAsNewEventAttributes? WorkflowExecutionContinuedAsNewEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionContinuedAsNewEventAttributes WorkflowExecutionContinuedAsNewEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionFailedEventAttributes? WorkflowExecutionFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionFailedEventAttributes WorkflowExecutionFailedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionOptionsUpdatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionOptionsUpdatedEventAttributes? WorkflowExecutionOptionsUpdatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionOptionsUpdatedEventAttributes WorkflowExecutionOptionsUpdatedEventAttributes { get; set; }
#endif
        /// <summary>Attributes for an event marking that a workflow execution was paused.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPausedEventAttributes? WorkflowExecutionPausedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPausedEventAttributes WorkflowExecutionPausedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionSignaledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionSignaledEventAttributes? WorkflowExecutionSignaledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionSignaledEventAttributes WorkflowExecutionSignaledEventAttributes { get; set; }
#endif
        /// <summary>Always the first event in workflow history</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionStartedEventAttributes? WorkflowExecutionStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionStartedEventAttributes WorkflowExecutionStartedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionTerminatedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTerminatedEventAttributes? WorkflowExecutionTerminatedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTerminatedEventAttributes WorkflowExecutionTerminatedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionTimedOutEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimedOutEventAttributes? WorkflowExecutionTimedOutEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimedOutEventAttributes WorkflowExecutionTimedOutEventAttributes { get; set; }
#endif
        /// <summary>Attributes for an event indicating that time skipping state changed for a workflow execution, either time was advanced or time skipping was disabled automatically due to a bound being reached. The worker_may_ignore field in HistoryEvent should always be set true for this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimeSkippingTransitionedEventAttributes? WorkflowExecutionTimeSkippingTransitionedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimeSkippingTransitionedEventAttributes WorkflowExecutionTimeSkippingTransitionedEventAttributes { get; set; }
#endif
        /// <summary>Attributes for an event marking that a workflow execution was unpaused.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUnpausedEventAttributes? WorkflowExecutionUnpausedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUnpausedEventAttributes WorkflowExecutionUnpausedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionUpdateAcceptedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAcceptedEventAttributes? WorkflowExecutionUpdateAcceptedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAcceptedEventAttributes WorkflowExecutionUpdateAcceptedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionUpdateAdmittedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAdmittedEventAttributes? WorkflowExecutionUpdateAdmittedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAdmittedEventAttributes WorkflowExecutionUpdateAdmittedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionUpdateCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateCompletedEventAttributes? WorkflowExecutionUpdateCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateCompletedEventAttributes WorkflowExecutionUpdateCompletedEventAttributes { get; set; }
#endif
        /// <summary>The workflowExecutionUpdateRejectedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes? WorkflowExecutionUpdateRejectedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes WorkflowExecutionUpdateRejectedEventAttributes { get; set; }
#endif
        /// <summary>The workflowPropertiesModifiedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedEventAttributes? WorkflowPropertiesModifiedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedEventAttributes WorkflowPropertiesModifiedEventAttributes { get; set; }
#endif
        /// <summary>Not used anywhere. Use case is replaced by WorkflowExecutionOptionsUpdatedEventAttributes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedExternallyEventAttributes? WorkflowPropertiesModifiedExternallyEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedExternallyEventAttributes WorkflowPropertiesModifiedExternallyEventAttributes { get; set; }
#endif
        /// <summary>The workflowTaskCompletedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskCompletedEventAttributes? WorkflowTaskCompletedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskCompletedEventAttributes WorkflowTaskCompletedEventAttributes { get; set; }
#endif
        /// <summary>The workflowTaskFailedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskFailedEventAttributes? WorkflowTaskFailedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskFailedEventAttributes WorkflowTaskFailedEventAttributes { get; set; }
#endif
        /// <summary>The workflowTaskScheduledEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskScheduledEventAttributes? WorkflowTaskScheduledEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskScheduledEventAttributes WorkflowTaskScheduledEventAttributes { get; set; }
#endif
        /// <summary>The workflowTaskStartedEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes? WorkflowTaskStartedEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes WorkflowTaskStartedEventAttributes { get; set; }
#endif
        /// <summary>The workflowTaskTimedOutEventAttributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskTimedOutEventAttributes? WorkflowTaskTimedOutEventAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskTimedOutEventAttributes WorkflowTaskTimedOutEventAttributes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent"/> and sets the default values.
        /// </summary>
        public HistoryEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activityPropertiesModifiedExternallyEventAttributes", n => { ActivityPropertiesModifiedExternallyEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityPropertiesModifiedExternallyEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityPropertiesModifiedExternallyEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskCancelRequestedEventAttributes", n => { ActivityTaskCancelRequestedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCancelRequestedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCancelRequestedEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskCanceledEventAttributes", n => { ActivityTaskCanceledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCanceledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCanceledEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskCompletedEventAttributes", n => { ActivityTaskCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskFailedEventAttributes", n => { ActivityTaskFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskScheduledEventAttributes", n => { ActivityTaskScheduledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskScheduledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskScheduledEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskStartedEventAttributes", n => { ActivityTaskStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "activityTaskTimedOutEventAttributes", n => { ActivityTaskTimedOutEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskTimedOutEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskTimedOutEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionCanceledEventAttributes", n => { ChildWorkflowExecutionCanceledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCanceledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCanceledEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionCompletedEventAttributes", n => { ChildWorkflowExecutionCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionFailedEventAttributes", n => { ChildWorkflowExecutionFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionStartedEventAttributes", n => { ChildWorkflowExecutionStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionTerminatedEventAttributes", n => { ChildWorkflowExecutionTerminatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTerminatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTerminatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "childWorkflowExecutionTimedOutEventAttributes", n => { ChildWorkflowExecutionTimedOutEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTimedOutEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTimedOutEventAttributes.CreateFromDiscriminatorValue); } },
                { "eventId", n => { EventId = n.GetStringValue(); } },
                { "eventTime", n => { EventTime = n.GetDateTimeOffsetValue(); } },
                { "eventType", n => { EventType = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent_eventType>(); } },
                { "externalWorkflowExecutionCancelRequestedEventAttributes", n => { ExternalWorkflowExecutionCancelRequestedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionCancelRequestedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionCancelRequestedEventAttributes.CreateFromDiscriminatorValue); } },
                { "externalWorkflowExecutionSignaledEventAttributes", n => { ExternalWorkflowExecutionSignaledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionSignaledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionSignaledEventAttributes.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>(global::Soenneker.Temporal.OpenApiClient.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "markerRecordedEventAttributes", n => { MarkerRecordedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.MarkerRecordedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.MarkerRecordedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationCancelRequestCompletedEventAttributes", n => { NexusOperationCancelRequestCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationCancelRequestFailedEventAttributes", n => { NexusOperationCancelRequestFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationCancelRequestedEventAttributes", n => { NexusOperationCancelRequestedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationCanceledEventAttributes", n => { NexusOperationCanceledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCanceledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCanceledEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationCompletedEventAttributes", n => { NexusOperationCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationFailedEventAttributes", n => { NexusOperationFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationScheduledEventAttributes", n => { NexusOperationScheduledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationScheduledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationScheduledEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationStartedEventAttributes", n => { NexusOperationStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "nexusOperationTimedOutEventAttributes", n => { NexusOperationTimedOutEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationTimedOutEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationTimedOutEventAttributes.CreateFromDiscriminatorValue); } },
                { "principal", n => { Principal = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Principal>(global::Soenneker.Temporal.OpenApiClient.Models.Principal.CreateFromDiscriminatorValue); } },
                { "requestCancelExternalWorkflowExecutionFailedEventAttributes", n => { RequestCancelExternalWorkflowExecutionFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "requestCancelExternalWorkflowExecutionInitiatedEventAttributes", n => { RequestCancelExternalWorkflowExecutionInitiatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionInitiatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionInitiatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "signalExternalWorkflowExecutionFailedEventAttributes", n => { SignalExternalWorkflowExecutionFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "signalExternalWorkflowExecutionInitiatedEventAttributes", n => { SignalExternalWorkflowExecutionInitiatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionInitiatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionInitiatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "startChildWorkflowExecutionFailedEventAttributes", n => { StartChildWorkflowExecutionFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "startChildWorkflowExecutionInitiatedEventAttributes", n => { StartChildWorkflowExecutionInitiatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionInitiatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionInitiatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "taskId", n => { TaskId = n.GetStringValue(); } },
                { "timerCanceledEventAttributes", n => { TimerCanceledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerCanceledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.TimerCanceledEventAttributes.CreateFromDiscriminatorValue); } },
                { "timerFiredEventAttributes", n => { TimerFiredEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerFiredEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.TimerFiredEventAttributes.CreateFromDiscriminatorValue); } },
                { "timerStartedEventAttributes", n => { TimerStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.TimerStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "upsertWorkflowSearchAttributesEventAttributes", n => { UpsertWorkflowSearchAttributesEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UpsertWorkflowSearchAttributesEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.UpsertWorkflowSearchAttributesEventAttributes.CreateFromDiscriminatorValue); } },
                { "userMetadata", n => { UserMetadata = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>(global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "workerMayIgnore", n => { WorkerMayIgnore = n.GetBoolValue(); } },
                { "workflowExecutionCancelRequestedEventAttributes", n => { WorkflowExecutionCancelRequestedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCancelRequestedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCancelRequestedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionCanceledEventAttributes", n => { WorkflowExecutionCanceledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCanceledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCanceledEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionCompletedEventAttributes", n => { WorkflowExecutionCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionContinuedAsNewEventAttributes", n => { WorkflowExecutionContinuedAsNewEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionContinuedAsNewEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionContinuedAsNewEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionFailedEventAttributes", n => { WorkflowExecutionFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionOptionsUpdatedEventAttributes", n => { WorkflowExecutionOptionsUpdatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionOptionsUpdatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionOptionsUpdatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionPausedEventAttributes", n => { WorkflowExecutionPausedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPausedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPausedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionSignaledEventAttributes", n => { WorkflowExecutionSignaledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionSignaledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionSignaledEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionStartedEventAttributes", n => { WorkflowExecutionStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionTerminatedEventAttributes", n => { WorkflowExecutionTerminatedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTerminatedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTerminatedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionTimeSkippingTransitionedEventAttributes", n => { WorkflowExecutionTimeSkippingTransitionedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimeSkippingTransitionedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimeSkippingTransitionedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionTimedOutEventAttributes", n => { WorkflowExecutionTimedOutEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimedOutEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimedOutEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionUnpausedEventAttributes", n => { WorkflowExecutionUnpausedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUnpausedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUnpausedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionUpdateAcceptedEventAttributes", n => { WorkflowExecutionUpdateAcceptedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAcceptedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAcceptedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionUpdateAdmittedEventAttributes", n => { WorkflowExecutionUpdateAdmittedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAdmittedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAdmittedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionUpdateCompletedEventAttributes", n => { WorkflowExecutionUpdateCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowExecutionUpdateRejectedEventAttributes", n => { WorkflowExecutionUpdateRejectedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowPropertiesModifiedEventAttributes", n => { WorkflowPropertiesModifiedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowPropertiesModifiedExternallyEventAttributes", n => { WorkflowPropertiesModifiedExternallyEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedExternallyEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedExternallyEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowTaskCompletedEventAttributes", n => { WorkflowTaskCompletedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskCompletedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskCompletedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowTaskFailedEventAttributes", n => { WorkflowTaskFailedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskFailedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskFailedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowTaskScheduledEventAttributes", n => { WorkflowTaskScheduledEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskScheduledEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskScheduledEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowTaskStartedEventAttributes", n => { WorkflowTaskStartedEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes.CreateFromDiscriminatorValue); } },
                { "workflowTaskTimedOutEventAttributes", n => { WorkflowTaskTimedOutEventAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskTimedOutEventAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskTimedOutEventAttributes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityPropertiesModifiedExternallyEventAttributes>("activityPropertiesModifiedExternallyEventAttributes", ActivityPropertiesModifiedExternallyEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCanceledEventAttributes>("activityTaskCanceledEventAttributes", ActivityTaskCanceledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCancelRequestedEventAttributes>("activityTaskCancelRequestedEventAttributes", ActivityTaskCancelRequestedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskCompletedEventAttributes>("activityTaskCompletedEventAttributes", ActivityTaskCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskFailedEventAttributes>("activityTaskFailedEventAttributes", ActivityTaskFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskScheduledEventAttributes>("activityTaskScheduledEventAttributes", ActivityTaskScheduledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskStartedEventAttributes>("activityTaskStartedEventAttributes", ActivityTaskStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ActivityTaskTimedOutEventAttributes>("activityTaskTimedOutEventAttributes", ActivityTaskTimedOutEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCanceledEventAttributes>("childWorkflowExecutionCanceledEventAttributes", ChildWorkflowExecutionCanceledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionCompletedEventAttributes>("childWorkflowExecutionCompletedEventAttributes", ChildWorkflowExecutionCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionFailedEventAttributes>("childWorkflowExecutionFailedEventAttributes", ChildWorkflowExecutionFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionStartedEventAttributes>("childWorkflowExecutionStartedEventAttributes", ChildWorkflowExecutionStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTerminatedEventAttributes>("childWorkflowExecutionTerminatedEventAttributes", ChildWorkflowExecutionTerminatedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ChildWorkflowExecutionTimedOutEventAttributes>("childWorkflowExecutionTimedOutEventAttributes", ChildWorkflowExecutionTimedOutEventAttributes);
            writer.WriteStringValue("eventId", EventId);
            writer.WriteDateTimeOffsetValue("eventTime", EventTime);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.HistoryEvent_eventType>("eventType", EventType);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionCancelRequestedEventAttributes>("externalWorkflowExecutionCancelRequestedEventAttributes", ExternalWorkflowExecutionCancelRequestedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ExternalWorkflowExecutionSignaledEventAttributes>("externalWorkflowExecutionSignaledEventAttributes", ExternalWorkflowExecutionSignaledEventAttributes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>("links", Links);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.MarkerRecordedEventAttributes>("markerRecordedEventAttributes", MarkerRecordedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCanceledEventAttributes>("nexusOperationCanceledEventAttributes", NexusOperationCanceledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestCompletedEventAttributes>("nexusOperationCancelRequestCompletedEventAttributes", NexusOperationCancelRequestCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestedEventAttributes>("nexusOperationCancelRequestedEventAttributes", NexusOperationCancelRequestedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCancelRequestFailedEventAttributes>("nexusOperationCancelRequestFailedEventAttributes", NexusOperationCancelRequestFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationCompletedEventAttributes>("nexusOperationCompletedEventAttributes", NexusOperationCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationFailedEventAttributes>("nexusOperationFailedEventAttributes", NexusOperationFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationScheduledEventAttributes>("nexusOperationScheduledEventAttributes", NexusOperationScheduledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationStartedEventAttributes>("nexusOperationStartedEventAttributes", NexusOperationStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationTimedOutEventAttributes>("nexusOperationTimedOutEventAttributes", NexusOperationTimedOutEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Principal>("principal", Principal);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionFailedEventAttributes>("requestCancelExternalWorkflowExecutionFailedEventAttributes", RequestCancelExternalWorkflowExecutionFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RequestCancelExternalWorkflowExecutionInitiatedEventAttributes>("requestCancelExternalWorkflowExecutionInitiatedEventAttributes", RequestCancelExternalWorkflowExecutionInitiatedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionFailedEventAttributes>("signalExternalWorkflowExecutionFailedEventAttributes", SignalExternalWorkflowExecutionFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalExternalWorkflowExecutionInitiatedEventAttributes>("signalExternalWorkflowExecutionInitiatedEventAttributes", SignalExternalWorkflowExecutionInitiatedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionFailedEventAttributes>("startChildWorkflowExecutionFailedEventAttributes", StartChildWorkflowExecutionFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.StartChildWorkflowExecutionInitiatedEventAttributes>("startChildWorkflowExecutionInitiatedEventAttributes", StartChildWorkflowExecutionInitiatedEventAttributes);
            writer.WriteStringValue("taskId", TaskId);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerCanceledEventAttributes>("timerCanceledEventAttributes", TimerCanceledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerFiredEventAttributes>("timerFiredEventAttributes", TimerFiredEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimerStartedEventAttributes>("timerStartedEventAttributes", TimerStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UpsertWorkflowSearchAttributesEventAttributes>("upsertWorkflowSearchAttributesEventAttributes", UpsertWorkflowSearchAttributesEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>("userMetadata", UserMetadata);
            writer.WriteStringValue("version", Version);
            writer.WriteBoolValue("workerMayIgnore", WorkerMayIgnore);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCanceledEventAttributes>("workflowExecutionCanceledEventAttributes", WorkflowExecutionCanceledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCancelRequestedEventAttributes>("workflowExecutionCancelRequestedEventAttributes", WorkflowExecutionCancelRequestedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionCompletedEventAttributes>("workflowExecutionCompletedEventAttributes", WorkflowExecutionCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionContinuedAsNewEventAttributes>("workflowExecutionContinuedAsNewEventAttributes", WorkflowExecutionContinuedAsNewEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionFailedEventAttributes>("workflowExecutionFailedEventAttributes", WorkflowExecutionFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionOptionsUpdatedEventAttributes>("workflowExecutionOptionsUpdatedEventAttributes", WorkflowExecutionOptionsUpdatedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPausedEventAttributes>("workflowExecutionPausedEventAttributes", WorkflowExecutionPausedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionSignaledEventAttributes>("workflowExecutionSignaledEventAttributes", WorkflowExecutionSignaledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionStartedEventAttributes>("workflowExecutionStartedEventAttributes", WorkflowExecutionStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTerminatedEventAttributes>("workflowExecutionTerminatedEventAttributes", WorkflowExecutionTerminatedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimedOutEventAttributes>("workflowExecutionTimedOutEventAttributes", WorkflowExecutionTimedOutEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionTimeSkippingTransitionedEventAttributes>("workflowExecutionTimeSkippingTransitionedEventAttributes", WorkflowExecutionTimeSkippingTransitionedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUnpausedEventAttributes>("workflowExecutionUnpausedEventAttributes", WorkflowExecutionUnpausedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAcceptedEventAttributes>("workflowExecutionUpdateAcceptedEventAttributes", WorkflowExecutionUpdateAcceptedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateAdmittedEventAttributes>("workflowExecutionUpdateAdmittedEventAttributes", WorkflowExecutionUpdateAdmittedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateCompletedEventAttributes>("workflowExecutionUpdateCompletedEventAttributes", WorkflowExecutionUpdateCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes>("workflowExecutionUpdateRejectedEventAttributes", WorkflowExecutionUpdateRejectedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedEventAttributes>("workflowPropertiesModifiedEventAttributes", WorkflowPropertiesModifiedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowPropertiesModifiedExternallyEventAttributes>("workflowPropertiesModifiedExternallyEventAttributes", WorkflowPropertiesModifiedExternallyEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskCompletedEventAttributes>("workflowTaskCompletedEventAttributes", WorkflowTaskCompletedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskFailedEventAttributes>("workflowTaskFailedEventAttributes", WorkflowTaskFailedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskScheduledEventAttributes>("workflowTaskScheduledEventAttributes", WorkflowTaskScheduledEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes>("workflowTaskStartedEventAttributes", WorkflowTaskStartedEventAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskTimedOutEventAttributes>("workflowTaskTimedOutEventAttributes", WorkflowTaskTimedOutEventAttributes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
