// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Summary of the current version of the Worker Deployment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A subset of information in ComputeConfig optimized for list views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.ComputeConfigSummary? ComputeConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.ComputeConfigSummary ComputeConfig { get; set; }
#endif
        /// <summary>The createTime property</summary>
        public DateTimeOffset? CreateTime { get; set; }
        /// <summary>&quot;Unset if not current. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &apos;Since&apos; captures the field semantics despite being a preposition. --)&quot;</summary>
        public DateTimeOffset? CurrentSinceTime { get; set; }
        /// <summary>Required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDeploymentVersion? DeploymentVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDeploymentVersion DeploymentVersion { get; set; }
#endif
        /// <summary>Information about workflow drainage to help the user determine when it is safe to decommission a Version. Not present while version is current or ramping</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageInfo? DrainageInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageInfo DrainageInfo { get; set; }
#endif
        /// <summary>Deprecated. Use `drainage_info` instead.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageStatus? DrainageStatus { get; set; }
        /// <summary>Timestamp when this version first became current or ramping.</summary>
        public DateTimeOffset? FirstActivationTime { get; set; }
        /// <summary>Timestamp when this version last became current. Can be used to determine whether a version has ever been Current.</summary>
        public DateTimeOffset? LastCurrentTime { get; set; }
        /// <summary>Timestamp when this version last stopped being current or ramping. Cleared if the version becomes current or ramping again.</summary>
        public DateTimeOffset? LastDeactivationTime { get; set; }
        /// <summary>&quot;Unset if not ramping. Updated when the version first starts ramping, not on each ramp change. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &apos;Since&apos; captures the field semantics despite being a preposition. --)&quot;</summary>
        public DateTimeOffset? RampingSinceTime { get; set; }
        /// <summary>Last time `current_since_time`, `ramping_since_time, or `ramp_percentage` of this version changed.</summary>
        public DateTimeOffset? RoutingUpdateTime { get; set; }
        /// <summary>The status of the Worker Deployment Version.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryStatus? Status { get; set; }
        /// <summary>Deprecated. Use `deployment_version`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary"/> and sets the default values.
        /// </summary>
        public ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.ListWorkerDeploymentsResponseWorkerDeploymentSummaryCurrentVersionSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "computeConfig", n => { ComputeConfig = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ComputeConfigSummary>(global::Soenneker.Temporal.OpenApiClient.Models.ComputeConfigSummary.CreateFromDiscriminatorValue); } },
                { "createTime", n => { CreateTime = n.GetDateTimeOffsetValue(); } },
                { "currentSinceTime", n => { CurrentSinceTime = n.GetDateTimeOffsetValue(); } },
                { "deploymentVersion", n => { DeploymentVersion = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDeploymentVersion>(global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDeploymentVersion.CreateFromDiscriminatorValue); } },
                { "drainageInfo", n => { DrainageInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageInfo>(global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageInfo.CreateFromDiscriminatorValue); } },
                { "drainageStatus", n => { DrainageStatus = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageStatus>(); } },
                { "firstActivationTime", n => { FirstActivationTime = n.GetDateTimeOffsetValue(); } },
                { "lastCurrentTime", n => { LastCurrentTime = n.GetDateTimeOffsetValue(); } },
                { "lastDeactivationTime", n => { LastDeactivationTime = n.GetDateTimeOffsetValue(); } },
                { "rampingSinceTime", n => { RampingSinceTime = n.GetDateTimeOffsetValue(); } },
                { "routingUpdateTime", n => { RoutingUpdateTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryStatus>(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.ComputeConfigSummary>("computeConfig", ComputeConfig);
            writer.WriteDateTimeOffsetValue("createTime", CreateTime);
            writer.WriteDateTimeOffsetValue("currentSinceTime", CurrentSinceTime);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDeploymentVersion>("deploymentVersion", DeploymentVersion);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageInfo>("drainageInfo", DrainageInfo);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryDrainageStatus>("drainageStatus", DrainageStatus);
            writer.WriteDateTimeOffsetValue("firstActivationTime", FirstActivationTime);
            writer.WriteDateTimeOffsetValue("lastCurrentTime", LastCurrentTime);
            writer.WriteDateTimeOffsetValue("lastDeactivationTime", LastDeactivationTime);
            writer.WriteDateTimeOffsetValue("rampingSinceTime", RampingSinceTime);
            writer.WriteDateTimeOffsetValue("routingUpdateTime", RoutingUpdateTime);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerDeploymentInfoWorkerDeploymentVersionSummaryStatus>("status", Status);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
