// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>A general status for this operation, indicates whether it is currently running or in one of the terminal statuses. Updated once when the operation is originally scheduled, and again when it reaches a terminal status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NexusOperationExecutionInfoStatus
    {
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_RUNNING")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusRunning,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_COMPLETED")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_FAILED")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_CANCELED")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_TERMINATED")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusTerminated,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_EXECUTION_STATUS_TIMED_OUT")]
        #pragma warning disable CS1591
        NexusOperationExecutionStatusTimedOut,
        #pragma warning restore CS1591
    }
}
