// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Full current state of a standalone Nexus operation, as of the time of the request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NexusOperationExecutionInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of attempts made to deliver the start operation request. This number is approximate, it is incremented when a task is added to the history queue. In practice, there could be more attempts if a task is executed but fails to commit, or less attempts if a task was never executed.</summary>
        public int? Attempt { get; set; }
        /// <summary>If the state is BLOCKED, blocked reason provides additional information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BlockedReason { get; set; }
#nullable restore
#else
        public string BlockedReason { get; set; }
#endif
        /// <summary>NexusOperationExecutionCancellationInfo contains the state of a Nexus operation cancellation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionCancellationInfo? CancellationInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionCancellationInfo CancellationInfo { get; set; }
#endif
        /// <summary>Time when the operation transitioned to a closed state.</summary>
        public DateTimeOffset? CloseTime { get; set; }
        /// <summary>Endpoint name, resolved to a URL via the cluster&apos;s endpoint registry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>Elapsed time from schedule_time to now for running operations or to close_time for closed operations, including all attempts and backoff between attempts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExecutionDuration { get; set; }
#nullable restore
#else
        public string ExecutionDuration { get; set; }
#endif
        /// <summary>Scheduled time + schedule to close timeout.</summary>
        public DateTimeOffset? ExpirationTime { get; set; }
        /// <summary>The identity of the client who started this operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>The time when the last attempt completed.</summary>
        public DateTimeOffset? LastAttemptCompleteTime { get; set; }
        /// <summary>The last attempt&apos;s failure, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure? LastAttemptFailure { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure LastAttemptFailure { get; set; }
#endif
        /// <summary>Links attached by the handler of this operation on start or completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link> Links { get; set; }
#endif
        /// <summary>The time when the next attempt is scheduled.</summary>
        public DateTimeOffset? NextAttemptScheduleTime { get; set; }
        /// <summary>Header for context propagation and tracing purposes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_nexusHeader? NexusHeader { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_nexusHeader NexusHeader { get; set; }
#endif
        /// <summary>Operation name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operation { get; set; }
#nullable restore
#else
        public string Operation { get; set; }
#endif
        /// <summary>Unique identifier of this Nexus operation within its namespace along with run ID (below).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationId { get; set; }
#nullable restore
#else
        public string OperationId { get; set; }
#endif
        /// <summary>Operation token. Only set for asynchronous operations after a successful StartOperation call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationToken { get; set; }
#nullable restore
#else
        public string OperationToken { get; set; }
#endif
        /// <summary>Server-generated request ID used as an idempotency token when submitting start requests to the handler. Distinct from the request_id in StartNexusOperationRequest, which is the caller-side idempotency key for the StartNexusOperation RPC itself.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>The runId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunId { get; set; }
#nullable restore
#else
        public string RunId { get; set; }
#endif
        /// <summary>Time the operation was originally scheduled via a StartNexusOperation request.</summary>
        public DateTimeOffset? ScheduleTime { get; set; }
        /// <summary>Schedule-to-close timeout for this operation. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &quot;to&quot; is used to indicate interval. --)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduleToCloseTimeout { get; set; }
#nullable restore
#else
        public string ScheduleToCloseTimeout { get; set; }
#endif
        /// <summary>Schedule-to-start timeout for this operation. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &quot;to&quot; is used to indicate interval. --)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduleToStartTimeout { get; set; }
#nullable restore
#else
        public string ScheduleToStartTimeout { get; set; }
#endif
        /// <summary>A user-defined set of *indexed* fields that are used/exposed when listing/searching workflows. The payload is not serialized in a user-defined way.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes? SearchAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes SearchAttributes { get; set; }
#endif
        /// <summary>Service name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Service { get; set; }
#nullable restore
#else
        public string Service { get; set; }
#endif
        /// <summary>Start-to-close timeout for this operation. (-- api-linter: core::0140::prepositions=disabled     aip.dev/not-precedent: &quot;to&quot; is used to indicate interval. --)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartToCloseTimeout { get; set; }
#nullable restore
#else
        public string StartToCloseTimeout { get; set; }
#endif
        /// <summary>More detailed breakdown of NEXUS_OPERATION_EXECUTION_STATUS_RUNNING.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_state? State { get; set; }
        /// <summary>Incremented each time the operation&apos;s state is mutated in persistence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateTransitionCount { get; set; }
#nullable restore
#else
        public string StateTransitionCount { get; set; }
#endif
        /// <summary>A general status for this operation, indicates whether it is currently running or in one of the terminal statuses. Updated once when the operation is originally scheduled, and again when it reaches a terminal status.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_status? Status { get; set; }
        /// <summary>Metadata for use by user interfaces to display the fixed as-of-start summary and details of the operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata? UserMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata UserMetadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo"/> and sets the default values.
        /// </summary>
        public NexusOperationExecutionInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attempt", n => { Attempt = n.GetIntValue(); } },
                { "blockedReason", n => { BlockedReason = n.GetStringValue(); } },
                { "cancellationInfo", n => { CancellationInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionCancellationInfo>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionCancellationInfo.CreateFromDiscriminatorValue); } },
                { "closeTime", n => { CloseTime = n.GetDateTimeOffsetValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "executionDuration", n => { ExecutionDuration = n.GetStringValue(); } },
                { "expirationTime", n => { ExpirationTime = n.GetDateTimeOffsetValue(); } },
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "lastAttemptCompleteTime", n => { LastAttemptCompleteTime = n.GetDateTimeOffsetValue(); } },
                { "lastAttemptFailure", n => { LastAttemptFailure = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>(global::Soenneker.Temporal.OpenApiClient.Models.Failure.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>(global::Soenneker.Temporal.OpenApiClient.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nextAttemptScheduleTime", n => { NextAttemptScheduleTime = n.GetDateTimeOffsetValue(); } },
                { "nexusHeader", n => { NexusHeader = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_nexusHeader>(global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_nexusHeader.CreateFromDiscriminatorValue); } },
                { "operation", n => { Operation = n.GetStringValue(); } },
                { "operationId", n => { OperationId = n.GetStringValue(); } },
                { "operationToken", n => { OperationToken = n.GetStringValue(); } },
                { "requestId", n => { RequestId = n.GetStringValue(); } },
                { "runId", n => { RunId = n.GetStringValue(); } },
                { "scheduleTime", n => { ScheduleTime = n.GetDateTimeOffsetValue(); } },
                { "scheduleToCloseTimeout", n => { ScheduleToCloseTimeout = n.GetStringValue(); } },
                { "scheduleToStartTimeout", n => { ScheduleToStartTimeout = n.GetStringValue(); } },
                { "searchAttributes", n => { SearchAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes.CreateFromDiscriminatorValue); } },
                { "service", n => { Service = n.GetStringValue(); } },
                { "startToCloseTimeout", n => { StartToCloseTimeout = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_state>(); } },
                { "stateTransitionCount", n => { StateTransitionCount = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_status>(); } },
                { "userMetadata", n => { UserMetadata = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>(global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attempt", Attempt);
            writer.WriteStringValue("blockedReason", BlockedReason);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionCancellationInfo>("cancellationInfo", CancellationInfo);
            writer.WriteDateTimeOffsetValue("closeTime", CloseTime);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("executionDuration", ExecutionDuration);
            writer.WriteDateTimeOffsetValue("expirationTime", ExpirationTime);
            writer.WriteStringValue("identity", Identity);
            writer.WriteDateTimeOffsetValue("lastAttemptCompleteTime", LastAttemptCompleteTime);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>("lastAttemptFailure", LastAttemptFailure);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>("links", Links);
            writer.WriteDateTimeOffsetValue("nextAttemptScheduleTime", NextAttemptScheduleTime);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_nexusHeader>("nexusHeader", NexusHeader);
            writer.WriteStringValue("operation", Operation);
            writer.WriteStringValue("operationId", OperationId);
            writer.WriteStringValue("operationToken", OperationToken);
            writer.WriteStringValue("requestId", RequestId);
            writer.WriteStringValue("runId", RunId);
            writer.WriteDateTimeOffsetValue("scheduleTime", ScheduleTime);
            writer.WriteStringValue("scheduleToCloseTimeout", ScheduleToCloseTimeout);
            writer.WriteStringValue("scheduleToStartTimeout", ScheduleToStartTimeout);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>("searchAttributes", SearchAttributes);
            writer.WriteStringValue("service", Service);
            writer.WriteStringValue("startToCloseTimeout", StartToCloseTimeout);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_state>("state", State);
            writer.WriteStringValue("stateTransitionCount", StateTransitionCount);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionInfo_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>("userMetadata", UserMetadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
