// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NexusOperationExecutionCancellationInfo_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_FAILED")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED")]
        #pragma warning disable CS1591
        NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED,
        #pragma warning restore CS1591
    }
}
