// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Limited Nexus operation information returned in the list response. When adding fields here, ensure that it is also present in NexusOperationExecutionInfo (note that it may already be present in NexusOperationExecutionInfo but not at the top-level).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NexusOperationExecutionListInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If the operation is in a terminal status, this field represents the time the operation transitioned to that status.</summary>
        public DateTimeOffset? CloseTime { get; set; }
        /// <summary>Endpoint name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>The difference between close time and scheduled time. This field is only populated if the operation is closed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExecutionDuration { get; set; }
#nullable restore
#else
        public string ExecutionDuration { get; set; }
#endif
        /// <summary>Operation name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operation { get; set; }
#nullable restore
#else
        public string Operation { get; set; }
#endif
        /// <summary>A unique identifier of this operation within its namespace along with run ID (below).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OperationId { get; set; }
#nullable restore
#else
        public string OperationId { get; set; }
#endif
        /// <summary>The run ID of the standalone Nexus operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunId { get; set; }
#nullable restore
#else
        public string RunId { get; set; }
#endif
        /// <summary>Time the operation was originally scheduled via a StartNexusOperation request.</summary>
        public DateTimeOffset? ScheduleTime { get; set; }
        /// <summary>Search attributes from the start request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes? SearchAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes SearchAttributes { get; set; }
#endif
        /// <summary>Service name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Service { get; set; }
#nullable restore
#else
        public string Service { get; set; }
#endif
        /// <summary>Updated on terminal status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateTransitionCount { get; set; }
#nullable restore
#else
        public string StateTransitionCount { get; set; }
#endif
        /// <summary>The status is updated once, when the operation is originally scheduled, and again when the operation reaches a terminal status.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo"/> and sets the default values.
        /// </summary>
        public NexusOperationExecutionListInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "closeTime", n => { CloseTime = n.GetDateTimeOffsetValue(); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "executionDuration", n => { ExecutionDuration = n.GetStringValue(); } },
                { "operation", n => { Operation = n.GetStringValue(); } },
                { "operationId", n => { OperationId = n.GetStringValue(); } },
                { "runId", n => { RunId = n.GetStringValue(); } },
                { "scheduleTime", n => { ScheduleTime = n.GetDateTimeOffsetValue(); } },
                { "searchAttributes", n => { SearchAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes.CreateFromDiscriminatorValue); } },
                { "service", n => { Service = n.GetStringValue(); } },
                { "stateTransitionCount", n => { StateTransitionCount = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("closeTime", CloseTime);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteStringValue("executionDuration", ExecutionDuration);
            writer.WriteStringValue("operation", Operation);
            writer.WriteStringValue("operationId", OperationId);
            writer.WriteStringValue("runId", RunId);
            writer.WriteDateTimeOffsetValue("scheduleTime", ScheduleTime);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>("searchAttributes", SearchAttributes);
            writer.WriteStringValue("service", Service);
            writer.WriteStringValue("stateTransitionCount", StateTransitionCount);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.NexusOperationExecutionListInfo_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
