// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PendingWorkflowTaskInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attempt property</summary>
        public int? Attempt { get; set; }
        /// <summary>original_scheduled_time is the scheduled time of the first workflow task during workflow task heartbeat. Heartbeat workflow task is done by RespondWorkflowTaskComplete with ForceCreateNewWorkflowTask == true and no command In this case, OriginalScheduledTime won&apos;t change. Then when current time - original_scheduled_time exceeds some threshold, the workflow task will be forced timeout.</summary>
        public DateTimeOffset? OriginalScheduledTime { get; set; }
        /// <summary>The scheduledTime property</summary>
        public DateTimeOffset? ScheduledTime { get; set; }
        /// <summary>The startedTime property</summary>
        public DateTimeOffset? StartedTime { get; set; }
        /// <summary>The state property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo_state? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo"/> and sets the default values.
        /// </summary>
        public PendingWorkflowTaskInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attempt", n => { Attempt = n.GetIntValue(); } },
                { "originalScheduledTime", n => { OriginalScheduledTime = n.GetDateTimeOffsetValue(); } },
                { "scheduledTime", n => { ScheduledTime = n.GetDateTimeOffsetValue(); } },
                { "startedTime", n => { StartedTime = n.GetDateTimeOffsetValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo_state>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attempt", Attempt);
            writer.WriteDateTimeOffsetValue("originalScheduledTime", OriginalScheduledTime);
            writer.WriteDateTimeOffsetValue("scheduledTime", ScheduledTime);
            writer.WriteDateTimeOffsetValue("startedTime", StartedTime);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.PendingWorkflowTaskInfo_state>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
