// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PendingActivityInfo_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_UNSPECIFIED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_SCHEDULED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_SCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_STARTED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_CANCEL_REQUESTED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_CANCEL_REQUESTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_PAUSED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_PAUSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ACTIVITY_STATE_PAUSE_REQUESTED")]
        #pragma warning disable CS1591
        PENDING_ACTIVITY_STATE_PAUSE_REQUESTED,
        #pragma warning restore CS1591
    }
}
