// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecordActivityTaskHeartbeatResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Will be set to true if the activity is paused.</summary>
        public bool? ActivityPaused { get; set; }
        /// <summary>Will be set to true if the activity was reset. Applies only to the current run.</summary>
        public bool? ActivityReset { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Will be set to true if the activity has been asked to cancel itself. The SDK should then notify the activity of cancellation if it is still running.</summary>
        public bool? CancelRequested { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse"/> and sets the default values.
        /// </summary>
        public RecordActivityTaskHeartbeatResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.RecordActivityTaskHeartbeatResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activityPaused", n => { ActivityPaused = n.GetBoolValue(); } },
                { "activityReset", n => { ActivityReset = n.GetBoolValue(); } },
                { "cancelRequested", n => { CancelRequested = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("activityPaused", ActivityPaused);
            writer.WriteBoolValue("activityReset", ActivityReset);
            writer.WriteBoolValue("cancelRequested", CancelRequested);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
