// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// ResetPointInfo records the workflow event id that is the first one processed by a given build id or binary checksum. A new reset point will be created if either build id or binary checksum changes (although in general only one or the other will be used at a time).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResetPointInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deprecated. A worker binary version identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BinaryChecksum { get; set; }
#nullable restore
#else
        public string BinaryChecksum { get; set; }
#endif
        /// <summary>Worker build id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildId { get; set; }
#nullable restore
#else
        public string BuildId { get; set; }
#endif
        /// <summary>The createTime property</summary>
        public DateTimeOffset? CreateTime { get; set; }
        /// <summary>(-- api-linter: core::0214::resource-expiry=disabled     aip.dev/not-precedent: TTL is not defined for ResetPointInfo. --) The time that the run is deleted due to retention.</summary>
        public DateTimeOffset? ExpireTime { get; set; }
        /// <summary>Event ID of the first WorkflowTaskCompleted event processed by this worker build.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstWorkflowTaskCompletedId { get; set; }
#nullable restore
#else
        public string FirstWorkflowTaskCompletedId { get; set; }
#endif
        /// <summary>false if the reset point has pending childWFs/reqCancels/signalExternals.</summary>
        public bool? Resettable { get; set; }
        /// <summary>The first run ID in the execution chain that was touched by this worker build.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RunId { get; set; }
#nullable restore
#else
        public string RunId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.ResetPointInfo"/> and sets the default values.
        /// </summary>
        public ResetPointInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.ResetPointInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.ResetPointInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.ResetPointInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "binaryChecksum", n => { BinaryChecksum = n.GetStringValue(); } },
                { "buildId", n => { BuildId = n.GetStringValue(); } },
                { "createTime", n => { CreateTime = n.GetDateTimeOffsetValue(); } },
                { "expireTime", n => { ExpireTime = n.GetDateTimeOffsetValue(); } },
                { "firstWorkflowTaskCompletedId", n => { FirstWorkflowTaskCompletedId = n.GetStringValue(); } },
                { "resettable", n => { Resettable = n.GetBoolValue(); } },
                { "runId", n => { RunId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("binaryChecksum", BinaryChecksum);
            writer.WriteStringValue("buildId", BuildId);
            writer.WriteDateTimeOffsetValue("createTime", CreateTime);
            writer.WriteDateTimeOffsetValue("expireTime", ExpireTime);
            writer.WriteStringValue("firstWorkflowTaskCompletedId", FirstWorkflowTaskCompletedId);
            writer.WriteBoolValue("resettable", Resettable);
            writer.WriteStringValue("runId", RunId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
