// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SchedulePolicies : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Policy for catchups: If the Temporal server misses an action due to one or more components being down, and comes back up, the action will be run if the scheduled time is within this window from the current time. This value defaults to one year, and can&apos;t be less than 10 seconds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CatchupWindow { get; set; }
#nullable restore
#else
        public string CatchupWindow { get; set; }
#endif
        /// <summary>If true, and the action would start a workflow, a timestamp will not be appended to the scheduled workflow id.</summary>
        public bool? KeepOriginalWorkflowId { get; set; }
        /// <summary>Policy for overlaps. Note that this can be changed after a schedule has taken some actions, and some changes might produce unintuitive results. In general, the later policy overrides the earlier policy.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies_overlapPolicy? OverlapPolicy { get; set; }
        /// <summary>If true, and a workflow run fails or times out, turn on &quot;paused&quot;. This applies after retry policies: the full chain of retries must fail to trigger a pause here.</summary>
        public bool? PauseOnFailure { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies"/> and sets the default values.
        /// </summary>
        public SchedulePolicies()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "catchupWindow", n => { CatchupWindow = n.GetStringValue(); } },
                { "keepOriginalWorkflowId", n => { KeepOriginalWorkflowId = n.GetBoolValue(); } },
                { "overlapPolicy", n => { OverlapPolicy = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies_overlapPolicy>(); } },
                { "pauseOnFailure", n => { PauseOnFailure = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("catchupWindow", CatchupWindow);
            writer.WriteBoolValue("keepOriginalWorkflowId", KeepOriginalWorkflowId);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SchedulePolicies_overlapPolicy>("overlapPolicy", OverlapPolicy);
            writer.WriteBoolValue("pauseOnFailure", PauseOnFailure);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
