// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Override the workflow to have Pinned behavior.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defaults to PINNED_OVERRIDE_BEHAVIOR_UNSPECIFIED. See `PinnedOverrideBehavior` for details.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_behavior? Behavior { get; set; }
        /// <summary>Specifies the Worker Deployment Version to pin this workflow to. Required if the target workflow is not already pinned to a version. If omitted and the target workflow is already pinned, the effective pinned version will be the existing pinned version. If omitted and the target workflow is not pinned, the override request will be rejected with a PreconditionFailed error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_version? Version { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_version Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned"/> and sets the default values.
        /// </summary>
        public SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "behavior", n => { Behavior = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_behavior>(); } },
                { "version", n => { Version = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_version>(global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_version.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_behavior>("behavior", Behavior);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_versioningOverride_pinned_version>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
