// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Defines how to resolve a workflow id conflict with a *running* workflow. The default policy is WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING. Note that WORKFLOW_ID_CONFLICT_POLICY_FAIL is an invalid option. See `workflow_id_reuse_policy` for handling a workflow id duplication with a *closed* workflow.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SignalWithStartWorkflowExecutionRequest_workflowIdConflictPolicy
    {
        [EnumMember(Value = "WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED")]
        #pragma warning disable CS1591
        WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_ID_CONFLICT_POLICY_FAIL")]
        #pragma warning disable CS1591
        WORKFLOW_ID_CONFLICT_POLICY_FAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING")]
        #pragma warning disable CS1591
        WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_ID_CONFLICT_POLICY_TERMINATE_EXISTING")]
        #pragma warning disable CS1591
        WORKFLOW_ID_CONFLICT_POLICY_TERMINATE_EXISTING,
        #pragma warning restore CS1591
    }
}
