// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SignalWithStartWorkflowExecutionRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Deprecated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Control { get; set; }
#nullable restore
#else
        public string Control { get; set; }
#endif
        /// <summary>See https://docs.temporal.io/docs/content/what-is-a-temporal-cron-job/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CronSchedule { get; set; }
#nullable restore
#else
        public string CronSchedule { get; set; }
#endif
        /// <summary>Contains metadata that can be attached to a variety of requests, like starting a workflow, and can be propagated between, for example, workflows and activities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Header? Header { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Header Header { get; set; }
#endif
        /// <summary>The identity of the worker/client</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>Serialized arguments to the workflow. These are passed as arguments to the workflow function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Payloads? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Payloads Input { get; set; }
#endif
        /// <summary>Links to be associated with the WorkflowExecutionStarted and WorkflowExecutionSignaled events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link>? Links { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Temporal.OpenApiClient.Models.Link> Links { get; set; }
#endif
        /// <summary>A user-defined set of *unindexed* fields that are exposed when listing/searching workflows</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Memo? Memo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Memo Memo { get; set; }
#endif
        /// <summary>The namespace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Namespace { get; set; }
#nullable restore
#else
        public string Namespace { get; set; }
#endif
        /// <summary>Priority metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Priority? Priority { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Priority Priority { get; set; }
#endif
        /// <summary>Used to de-dupe signal w/ start requests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>Retry policy for the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.RetryPolicy? RetryPolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.RetryPolicy RetryPolicy { get; set; }
#endif
        /// <summary>A user-defined set of *indexed* fields that are used/exposed when listing/searching workflows. The payload is not serialized in a user-defined way.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes? SearchAttributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes SearchAttributes { get; set; }
#endif
        /// <summary>Serialized value(s) to provide with the signal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Payloads? SignalInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Payloads SignalInput { get; set; }
#endif
        /// <summary>The workflow author-defined name of the signal to send to the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignalName { get; set; }
#nullable restore
#else
        public string SignalName { get; set; }
#endif
        /// <summary>The task queue to start this workflow on, if it will be started</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueue? TaskQueue { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TaskQueue TaskQueue { get; set; }
#endif
        /// <summary>Time-skipping configuration. If not set, time skipping is disabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig? TimeSkippingConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig TimeSkippingConfig { get; set; }
#endif
        /// <summary>Metadata on the workflow if it is started. This is carried over to the WorkflowExecutionInfo for use by user interfaces to display the fixed as-of-start summary and details of the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata? UserMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata UserMetadata { get; set; }
#endif
        /// <summary>If set, takes precedence over the Versioning Behavior sent by the SDK on Workflow Task completion. To unset the override after the workflow is running, use UpdateWorkflowExecutionOptions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverride? VersioningOverride { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverride VersioningOverride { get; set; }
#endif
        /// <summary>Total workflow execution timeout including retries and continue as new</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowExecutionTimeout { get; set; }
#nullable restore
#else
        public string WorkflowExecutionTimeout { get; set; }
#endif
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>Defines how to resolve a workflow id conflict with a *running* workflow. The default policy is WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING. Note that WORKFLOW_ID_CONFLICT_POLICY_FAIL is an invalid option. See `workflow_id_reuse_policy` for handling a workflow id duplication with a *closed* workflow.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdConflictPolicy? WorkflowIdConflictPolicy { get; set; }
        /// <summary>Defines whether to allow re-using the workflow id from a previously *closed* workflow. The default policy is WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE. See `workflow_id_reuse_policy` for handling a workflow id duplication with a *running* workflow.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdReusePolicy? WorkflowIdReusePolicy { get; set; }
        /// <summary>Timeout of a single workflow run</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowRunTimeout { get; set; }
#nullable restore
#else
        public string WorkflowRunTimeout { get; set; }
#endif
        /// <summary>Time to wait before dispatching the first workflow task. Cannot be used with `cron_schedule`. Note that the signal will be delivered with the first workflow task. If the workflow gets another SignalWithStartWorkflow before the delay a workflow task will be dispatched immediately and the rest of the delay period will be ignored, even if that request also had a delay. Signal via SignalWorkflowExecution will not unblock the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowStartDelay { get; set; }
#nullable restore
#else
        public string WorkflowStartDelay { get; set; }
#endif
        /// <summary>Timeout of a single workflow task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowTaskTimeout { get; set; }
#nullable restore
#else
        public string WorkflowTaskTimeout { get; set; }
#endif
        /// <summary>Represents the identifier used by a workflow author to define the workflow. Typically, the name of a function. This is sometimes referred to as the workflow&apos;s &quot;name&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowType? WorkflowType { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowType WorkflowType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest"/> and sets the default values.
        /// </summary>
        public SignalWithStartWorkflowExecutionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "control", n => { Control = n.GetStringValue(); } },
                { "cronSchedule", n => { CronSchedule = n.GetStringValue(); } },
                { "header", n => { Header = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Header>(global::Soenneker.Temporal.OpenApiClient.Models.Header.CreateFromDiscriminatorValue); } },
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Payloads>(global::Soenneker.Temporal.OpenApiClient.Models.Payloads.CreateFromDiscriminatorValue); } },
                { "links", n => { Links = n.GetCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>(global::Soenneker.Temporal.OpenApiClient.Models.Link.CreateFromDiscriminatorValue)?.AsList(); } },
                { "memo", n => { Memo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Memo>(global::Soenneker.Temporal.OpenApiClient.Models.Memo.CreateFromDiscriminatorValue); } },
                { "namespace", n => { Namespace = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Priority>(global::Soenneker.Temporal.OpenApiClient.Models.Priority.CreateFromDiscriminatorValue); } },
                { "requestId", n => { RequestId = n.GetStringValue(); } },
                { "retryPolicy", n => { RetryPolicy = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RetryPolicy>(global::Soenneker.Temporal.OpenApiClient.Models.RetryPolicy.CreateFromDiscriminatorValue); } },
                { "searchAttributes", n => { SearchAttributes = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>(global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes.CreateFromDiscriminatorValue); } },
                { "signalInput", n => { SignalInput = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Payloads>(global::Soenneker.Temporal.OpenApiClient.Models.Payloads.CreateFromDiscriminatorValue); } },
                { "signalName", n => { SignalName = n.GetStringValue(); } },
                { "taskQueue", n => { TaskQueue = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueue>(global::Soenneker.Temporal.OpenApiClient.Models.TaskQueue.CreateFromDiscriminatorValue); } },
                { "timeSkippingConfig", n => { TimeSkippingConfig = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig>(global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig.CreateFromDiscriminatorValue); } },
                { "userMetadata", n => { UserMetadata = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>(global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata.CreateFromDiscriminatorValue); } },
                { "versioningOverride", n => { VersioningOverride = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverride>(global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverride.CreateFromDiscriminatorValue); } },
                { "workflowExecutionTimeout", n => { WorkflowExecutionTimeout = n.GetStringValue(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
                { "workflowIdConflictPolicy", n => { WorkflowIdConflictPolicy = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdConflictPolicy>(); } },
                { "workflowIdReusePolicy", n => { WorkflowIdReusePolicy = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdReusePolicy>(); } },
                { "workflowRunTimeout", n => { WorkflowRunTimeout = n.GetStringValue(); } },
                { "workflowStartDelay", n => { WorkflowStartDelay = n.GetStringValue(); } },
                { "workflowTaskTimeout", n => { WorkflowTaskTimeout = n.GetStringValue(); } },
                { "workflowType", n => { WorkflowType = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowType>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowType.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("control", Control);
            writer.WriteStringValue("cronSchedule", CronSchedule);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Header>("header", Header);
            writer.WriteStringValue("identity", Identity);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Payloads>("input", Input);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Temporal.OpenApiClient.Models.Link>("links", Links);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Memo>("memo", Memo);
            writer.WriteStringValue("namespace", Namespace);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Priority>("priority", Priority);
            writer.WriteStringValue("requestId", RequestId);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.RetryPolicy>("retryPolicy", RetryPolicy);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.SearchAttributes>("searchAttributes", SearchAttributes);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Payloads>("signalInput", SignalInput);
            writer.WriteStringValue("signalName", SignalName);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TaskQueue>("taskQueue", TaskQueue);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig>("timeSkippingConfig", TimeSkippingConfig);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.UserMetadata>("userMetadata", UserMetadata);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverride>("versioningOverride", VersioningOverride);
            writer.WriteStringValue("workflowExecutionTimeout", WorkflowExecutionTimeout);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdConflictPolicy>("workflowIdConflictPolicy", WorkflowIdConflictPolicy);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.SignalWithStartWorkflowExecutionRequest_workflowIdReusePolicy>("workflowIdReusePolicy", WorkflowIdReusePolicy);
            writer.WriteStringValue("workflowRunTimeout", WorkflowRunTimeout);
            writer.WriteStringValue("workflowStartDelay", WorkflowStartDelay);
            writer.WriteStringValue("workflowTaskTimeout", WorkflowTaskTimeout);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowType>("workflowType", WorkflowType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
