// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SignalExternalWorkflowExecutionFailedEventAttributesCause
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED")]
        #pragma warning disable CS1591
        SignalExternalWorkflowExecutionFailedCauseUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND")]
        #pragma warning disable CS1591
        SignalExternalWorkflowExecutionFailedCauseExternalWorkflowExecutionNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_NAMESPACE_NOT_FOUND")]
        #pragma warning disable CS1591
        SignalExternalWorkflowExecutionFailedCauseNamespaceNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_SIGNAL_COUNT_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        SignalExternalWorkflowExecutionFailedCauseSignalCountLimitExceeded,
        #pragma warning restore CS1591
    }
}
