// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Default: PARENT_CLOSE_POLICY_TERMINATE.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StartChildWorkflowExecutionInitiatedEventAttributes_parentClosePolicy
    {
        [EnumMember(Value = "PARENT_CLOSE_POLICY_UNSPECIFIED")]
        #pragma warning disable CS1591
        PARENT_CLOSE_POLICY_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARENT_CLOSE_POLICY_TERMINATE")]
        #pragma warning disable CS1591
        PARENT_CLOSE_POLICY_TERMINATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARENT_CLOSE_POLICY_ABANDON")]
        #pragma warning disable CS1591
        PARENT_CLOSE_POLICY_ABANDON,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARENT_CLOSE_POLICY_REQUEST_CANCEL")]
        #pragma warning disable CS1591
        PARENT_CLOSE_POLICY_REQUEST_CANCEL,
        #pragma warning restore CS1591
    }
}
