// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Link to the workflow event.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StartWorkflowExecutionResponseLink : IAdditionalDataHolder, IParsable
    {
        /// <summary>A link to an activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkActivity? Activity { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkActivity Activity { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A link to a built-in batch job. Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc). This link can be put on workflow history events generated by actions taken by a batch job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkBatchJob? BatchJob { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkBatchJob BatchJob { get; set; }
#endif
        /// <summary>A link to a standalone Nexus operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkNexusOperation? NexusOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkNexusOperation NexusOperation { get; set; }
#endif
        /// <summary>A link to a workflow execution. This is a more general version of WorkflowEvent that doesn&apos;t specify a  particular event within the workflow, useful when you want to link to a workflow but there is no particular event to link to, such as a Query or a Rejected Update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflow? Workflow { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflow Workflow { get; set; }
#endif
        /// <summary>The workflowEvent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflowEvent? WorkflowEvent { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflowEvent WorkflowEvent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.StartWorkflowExecutionResponseLink"/> and sets the default values.
        /// </summary>
        public StartWorkflowExecutionResponseLink()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.StartWorkflowExecutionResponseLink"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.StartWorkflowExecutionResponseLink CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.StartWorkflowExecutionResponseLink();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkActivity>(global::Soenneker.Temporal.OpenApiClient.Models.LinkActivity.CreateFromDiscriminatorValue); } },
                { "batchJob", n => { BatchJob = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkBatchJob>(global::Soenneker.Temporal.OpenApiClient.Models.LinkBatchJob.CreateFromDiscriminatorValue); } },
                { "nexusOperation", n => { NexusOperation = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkNexusOperation>(global::Soenneker.Temporal.OpenApiClient.Models.LinkNexusOperation.CreateFromDiscriminatorValue); } },
                { "workflow", n => { Workflow = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflow>(global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflow.CreateFromDiscriminatorValue); } },
                { "workflowEvent", n => { WorkflowEvent = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflowEvent>(global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflowEvent.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkActivity>("activity", Activity);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkBatchJob>("batchJob", BatchJob);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkNexusOperation>("nexusOperation", NexusOperation);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflow>("workflow", Workflow);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.LinkWorkflowEvent>("workflowEvent", WorkflowEvent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
