// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Current execution status of the workflow. Typically remains WORKFLOW_EXECUTION_STATUS_RUNNING unless a de-dupe occurs or in specific scenarios handled within the ExecuteMultiOperation (refer to its docs).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StartWorkflowExecutionResponseStatus
    {
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_RUNNING")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusRunning,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_COMPLETED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_FAILED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_CANCELED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_TERMINATED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusTerminated,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusContinuedAsNew,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_TIMED_OUT")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusTimedOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_EXECUTION_STATUS_PAUSED")]
        #pragma warning disable CS1591
        WorkflowExecutionStatusPaused,
        #pragma warning restore CS1591
    }
}
