// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for time skipping during a workflow execution. When enabled, virtual time advances automatically whenever there is no in-flight work. In-flight work includes activities, child workflows, Nexus operations, signal/cancel external workflow operations, and possibly other features added in the future. User timers are not classified as in-flight work and will be skipped over. When time advances, it skips to the earlier of the next user timer or the configured bound, if either exists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeSkippingConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If set, the enabled field is not propagated to transitively related workflows.</summary>
        public bool? DisablePropagation { get; set; }
        /// <summary>Enables or disables time skipping for this workflow execution. By default, this field is propagated to transitively related workflows (child workflows/start-as-new/reset)  at the time they are started. Changes made after a transitively related workflow has started are not propagated.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Maximum elapsed time since time skipping was enabled. This includes both skipped time and real time elapsing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxElapsedDuration { get; set; }
#nullable restore
#else
        public string MaxElapsedDuration { get; set; }
#endif
        /// <summary>Maximum total virtual time that can be skipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxSkippedDuration { get; set; }
#nullable restore
#else
        public string MaxSkippedDuration { get; set; }
#endif
        /// <summary>Absolute virtual timestamp at which time skipping is disabled. Time skipping will not advance beyond this point.</summary>
        public DateTimeOffset? MaxTargetTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig"/> and sets the default values.
        /// </summary>
        public TimeSkippingConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.TimeSkippingConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disablePropagation", n => { DisablePropagation = n.GetBoolValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "maxElapsedDuration", n => { MaxElapsedDuration = n.GetStringValue(); } },
                { "maxSkippedDuration", n => { MaxSkippedDuration = n.GetStringValue(); } },
                { "maxTargetTime", n => { MaxTargetTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("disablePropagation", DisablePropagation);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("maxElapsedDuration", MaxElapsedDuration);
            writer.WriteStringValue("maxSkippedDuration", MaxSkippedDuration);
            writer.WriteDateTimeOffsetValue("maxTargetTime", MaxTargetTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
