// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// The worker configuration. Will be returned if the command was sent to a single worker.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateWorkerConfigResponse_workerConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoscalingPollerBehavior property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigAutoscalingPollerBehavior? AutoscalingPollerBehavior { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigAutoscalingPollerBehavior AutoscalingPollerBehavior { get; set; }
#endif
        /// <summary>The simplePollerBehavior property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigSimplePollerBehavior? SimplePollerBehavior { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigSimplePollerBehavior SimplePollerBehavior { get; set; }
#endif
        /// <summary>The workflowCacheSize property</summary>
        public int? WorkflowCacheSize { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.UpdateWorkerConfigResponse_workerConfig"/> and sets the default values.
        /// </summary>
        public UpdateWorkerConfigResponse_workerConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.UpdateWorkerConfigResponse_workerConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.UpdateWorkerConfigResponse_workerConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.UpdateWorkerConfigResponse_workerConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoscalingPollerBehavior", n => { AutoscalingPollerBehavior = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigAutoscalingPollerBehavior>(global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigAutoscalingPollerBehavior.CreateFromDiscriminatorValue); } },
                { "simplePollerBehavior", n => { SimplePollerBehavior = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigSimplePollerBehavior>(global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigSimplePollerBehavior.CreateFromDiscriminatorValue); } },
                { "workflowCacheSize", n => { WorkflowCacheSize = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigAutoscalingPollerBehavior>("autoscalingPollerBehavior", AutoscalingPollerBehavior);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfigSimplePollerBehavior>("simplePollerBehavior", SimplePollerBehavior);
            writer.WriteIntValue("workflowCacheSize", WorkflowCacheSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
