// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Set to DRAINING when the version first stops accepting new executions (is no longer current or ramping). Set to DRAINED when no more open pinned workflows exist on this version.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VersionDrainageInfo_status
    {
        [EnumMember(Value = "VERSION_DRAINAGE_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        VERSION_DRAINAGE_STATUS_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERSION_DRAINAGE_STATUS_DRAINING")]
        #pragma warning disable CS1591
        VERSION_DRAINAGE_STATUS_DRAINING,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERSION_DRAINAGE_STATUS_DRAINED")]
        #pragma warning disable CS1591
        VERSION_DRAINAGE_STATUS_DRAINED,
        #pragma warning restore CS1591
    }
}
