// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>&quot;Indicates the Update lifecycle stage that the Update must reach before API call is returned. NOTE: This field works together with API call timeout which is limited by server timeout (maximum wait time). If server timeout is expired before user specified timeout, API call returns even if specified stage is not reached.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WaitPolicyLifecycleStage
    {
        [EnumMember(Value = "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_UNSPECIFIED")]
        #pragma warning disable CS1591
        UpdateWorkflowExecutionLifecycleStageUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ADMITTED")]
        #pragma warning disable CS1591
        UpdateWorkflowExecutionLifecycleStageAdmitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ACCEPTED")]
        #pragma warning disable CS1591
        UpdateWorkflowExecutionLifecycleStageAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED")]
        #pragma warning disable CS1591
        UpdateWorkflowExecutionLifecycleStageCompleted,
        #pragma warning restore CS1591
    }
}
