// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Holds all the extra information about workflow execution that is not part of Visibility.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowExecutionExtendedInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>indicates if the workflow received a cancel request</summary>
        public bool? CancelRequested { get; set; }
        /// <summary>Workflow execution expiration time is defined as workflow start time plus expiration timeout. Workflow start time may change after workflow reset.</summary>
        public DateTimeOffset? ExecutionExpirationTime { get; set; }
        /// <summary>Last workflow reset time. Nil if the workflow was never reset.</summary>
        public DateTimeOffset? LastResetTime { get; set; }
        /// <summary>Original workflow start time.</summary>
        public DateTimeOffset? OriginalStartTime { get; set; }
        /// <summary>Information about the workflow execution pause operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPauseInfo? PauseInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPauseInfo PauseInfo { get; set; }
#endif
        /// <summary>Request ID information (eg: history event information associated with the request ID). Note: It only contains request IDs from StartWorkflowExecution requests, including indirect calls (eg: if SignalWithStartWorkflowExecution starts a new workflow, then the request ID is used in the StartWorkflowExecution request).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo_requestIdInfos? RequestIdInfos { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo_requestIdInfos RequestIdInfos { get; set; }
#endif
        /// <summary>Reset Run ID points to the new run when this execution is reset. If the execution is reset multiple times, it points to the latest run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetRunId { get; set; }
#nullable restore
#else
        public string ResetRunId { get; set; }
#endif
        /// <summary>Workflow run expiration time is defined as current workflow run start time plus workflow run timeout.</summary>
        public DateTimeOffset? RunExpirationTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo"/> and sets the default values.
        /// </summary>
        public WorkflowExecutionExtendedInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cancelRequested", n => { CancelRequested = n.GetBoolValue(); } },
                { "executionExpirationTime", n => { ExecutionExpirationTime = n.GetDateTimeOffsetValue(); } },
                { "lastResetTime", n => { LastResetTime = n.GetDateTimeOffsetValue(); } },
                { "originalStartTime", n => { OriginalStartTime = n.GetDateTimeOffsetValue(); } },
                { "pauseInfo", n => { PauseInfo = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPauseInfo>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPauseInfo.CreateFromDiscriminatorValue); } },
                { "requestIdInfos", n => { RequestIdInfos = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo_requestIdInfos>(global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo_requestIdInfos.CreateFromDiscriminatorValue); } },
                { "resetRunId", n => { ResetRunId = n.GetStringValue(); } },
                { "runExpirationTime", n => { RunExpirationTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cancelRequested", CancelRequested);
            writer.WriteDateTimeOffsetValue("executionExpirationTime", ExecutionExpirationTime);
            writer.WriteDateTimeOffsetValue("lastResetTime", LastResetTime);
            writer.WriteDateTimeOffsetValue("originalStartTime", OriginalStartTime);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionPauseInfo>("pauseInfo", PauseInfo);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionExtendedInfo_requestIdInfos>("requestIdInfos", RequestIdInfos);
            writer.WriteStringValue("resetRunId", ResetRunId);
            writer.WriteDateTimeOffsetValue("runExpirationTime", RunExpirationTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
