// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Required. Versioning Mode for this worker. Must be the same for all workers with the same `deployment_name` and `build_id` combination, across all Task Queues. When `worker_versioning_mode==VERSIONED`, the worker will be part of a Deployment Version.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkerDeploymentOptionsWorkerVersioningMode
    {
        [EnumMember(Value = "WORKER_VERSIONING_MODE_UNSPECIFIED")]
        #pragma warning disable CS1591
        WorkerVersioningModeUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKER_VERSIONING_MODE_UNVERSIONED")]
        #pragma warning disable CS1591
        WorkerVersioningModeUnversioned,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKER_VERSIONING_MODE_VERSIONED")]
        #pragma warning disable CS1591
        WorkerVersioningModeVersioned,
        #pragma warning restore CS1591
    }
}
