// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowTaskFailedEventAttributes_cause
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_MODIFY_WORKFLOW_PROPERTIES_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_MODIFY_WORKFLOW_PROPERTIES_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_CHILD_WORKFLOWS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PENDING_CHILD_WORKFLOWS_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_ACTIVITIES_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PENDING_ACTIVITIES_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_SIGNALS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PENDING_SIGNALS_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_REQUEST_CANCEL_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PENDING_REQUEST_CANCEL_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_UPDATE_WORKFLOW_EXECUTION_MESSAGE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_UPDATE_WORKFLOW_EXECUTION_MESSAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_UPDATE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_UPDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_NEXUS_OPERATION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_NEXUS_OPERATION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_NEXUS_OPERATIONS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PENDING_NEXUS_OPERATIONS_LIMIT_EXCEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_NEXUS_OPERATION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_NEXUS_OPERATION_ATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FEATURE_DISABLED")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_FEATURE_DISABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_GRPC_MESSAGE_TOO_LARGE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_GRPC_MESSAGE_TOO_LARGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PAYLOADS_TOO_LARGE")]
        #pragma warning disable CS1591
        WORKFLOW_TASK_FAILED_CAUSE_PAYLOADS_TOO_LARGE,
        #pragma warning restore CS1591
    }
}
