// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowTaskStartedEventAttributes_suggestContinueAsNewReasons
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SUGGEST_CONTINUE_AS_NEW_REASON_UNSPECIFIED")]
        #pragma warning disable CS1591
        SUGGEST_CONTINUE_AS_NEW_REASON_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUGGEST_CONTINUE_AS_NEW_REASON_HISTORY_SIZE_TOO_LARGE")]
        #pragma warning disable CS1591
        SUGGEST_CONTINUE_AS_NEW_REASON_HISTORY_SIZE_TOO_LARGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUGGEST_CONTINUE_AS_NEW_REASON_TOO_MANY_HISTORY_EVENTS")]
        #pragma warning disable CS1591
        SUGGEST_CONTINUE_AS_NEW_REASON_TOO_MANY_HISTORY_EVENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUGGEST_CONTINUE_AS_NEW_REASON_TOO_MANY_UPDATES")]
        #pragma warning disable CS1591
        SUGGEST_CONTINUE_AS_NEW_REASON_TOO_MANY_UPDATES,
        #pragma warning restore CS1591
    }
}
