// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkerConfig_AutoscalingPollerBehavior : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This many polls will be attempted initially before scaling kicks in. Must be between  `minimum` and `maximum`.</summary>
        public int? InitialPollers { get; set; }
        /// <summary>At most this many poll calls will ever be open at once. Must be &gt;= `minimum`.</summary>
        public int? MaxPollers { get; set; }
        /// <summary>At least this many poll calls will always be attempted (assuming slots are available). Cannot be zero.</summary>
        public int? MinPollers { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfig_AutoscalingPollerBehavior"/> and sets the default values.
        /// </summary>
        public WorkerConfig_AutoscalingPollerBehavior()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfig_AutoscalingPollerBehavior"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfig_AutoscalingPollerBehavior CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.WorkerConfig_AutoscalingPollerBehavior();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "initialPollers", n => { InitialPollers = n.GetIntValue(); } },
                { "maxPollers", n => { MaxPollers = n.GetIntValue(); } },
                { "minPollers", n => { MinPollers = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("initialPollers", InitialPollers);
            writer.WriteIntValue("maxPollers", MaxPollers);
            writer.WriteIntValue("minPollers", MinPollers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
