// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowTaskFailedEventAttributesCause
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseUnhandledCommand,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadScheduleActivityAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadRequestCancelActivityAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadStartTimerAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadCancelTimerAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadRecordMarkerAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadCompleteWorkflowExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadFailWorkflowExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadCancelWorkflowExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadRequestCancelExternalWorkflowExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadContinueAsNewAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseStartTimerDuplicateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseResetStickyTaskQueue,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseWorkflowWorkerUnhandledFailure,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadSignalWorkflowExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadStartChildExecutionAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseForceCloseCommand,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseFailoverCloseCommand,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadSignalInputSize,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseResetWorkflow,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadBinary,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseScheduleActivityDuplicateId,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadSearchAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseNonDeterministicError,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_MODIFY_WORKFLOW_PROPERTIES_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadModifyWorkflowPropertiesAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_CHILD_WORKFLOWS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePendingChildWorkflowsLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_ACTIVITIES_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePendingActivitiesLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_SIGNALS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePendingSignalsLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_REQUEST_CANCEL_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePendingRequestCancelLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_UPDATE_WORKFLOW_EXECUTION_MESSAGE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadUpdateWorkflowExecutionMessage,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_UPDATE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseUnhandledUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_NEXUS_OPERATION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadScheduleNexusOperationAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PENDING_NEXUS_OPERATIONS_LIMIT_EXCEEDED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePendingNexusOperationsLimitExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_NEXUS_OPERATION_ATTRIBUTES")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseBadRequestCancelNexusOperationAttributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_FEATURE_DISABLED")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseFeatureDisabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_GRPC_MESSAGE_TOO_LARGE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCauseGrpcMessageTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "WORKFLOW_TASK_FAILED_CAUSE_PAYLOADS_TOO_LARGE")]
        #pragma warning disable CS1591
        WorkflowTaskFailedCausePayloadsTooLarge,
        #pragma warning restore CS1591
    }
}
