// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>
    /// Present if user has set an execution-specific versioning override. This override takes precedence over SDK-sent `behavior` (and `version` when override is PINNED). An override can be set when starting a new execution, as well as afterwards by calling the `UpdateWorkflowExecutionOptions` API. Pinned overrides are automatically inherited by child workflows, continue-as-new workflows, workflow retries, and cron workflows.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowExecutionVersioningInfoVersioningOverride : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Override the workflow to have AutoUpgrade behavior.</summary>
        public bool? AutoUpgrade { get; set; }
        /// <summary>Required. Deprecated. Use `override`.</summary>
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideBehavior? Behavior { get; set; }
        /// <summary>Required if behavior is `PINNED`. Must be null if behavior is `AUTO_UPGRADE`. Identifies the worker deployment to pin the workflow to. Deprecated. Use `override.pinned.version`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideDeployment? Deployment { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideDeployment Deployment { get; set; }
#endif
        /// <summary>Override the workflow to have Pinned behavior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverridePinned? Pinned { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverridePinned Pinned { get; set; }
#endif
        /// <summary>Required if behavior is `PINNED`. Must be absent if behavior is not `PINNED`. Identifies the worker deployment version to pin the workflow to, in the format &quot;&lt;deployment_name&gt;.&lt;build_id&gt;&quot;. Deprecated. Use `override.pinned.version`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PinnedVersion { get; set; }
#nullable restore
#else
        public string PinnedVersion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionVersioningInfoVersioningOverride"/> and sets the default values.
        /// </summary>
        public WorkflowExecutionVersioningInfoVersioningOverride()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionVersioningInfoVersioningOverride"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionVersioningInfoVersioningOverride CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionVersioningInfoVersioningOverride();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoUpgrade", n => { AutoUpgrade = n.GetBoolValue(); } },
                { "behavior", n => { Behavior = n.GetEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideBehavior>(); } },
                { "deployment", n => { Deployment = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideDeployment>(global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideDeployment.CreateFromDiscriminatorValue); } },
                { "pinned", n => { Pinned = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverridePinned>(global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverridePinned.CreateFromDiscriminatorValue); } },
                { "pinnedVersion", n => { PinnedVersion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoUpgrade", AutoUpgrade);
            writer.WriteEnumValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideBehavior>("behavior", Behavior);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverrideDeployment>("deployment", Deployment);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.VersioningOverridePinned>("pinned", Pinned);
            writer.WriteStringValue("pinnedVersion", PinnedVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
