// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowTaskStartedEventAttributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Used by server internally to properly reapply build ID redirects to an execution when rebuilding it from events. Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildIdRedirectCounter { get; set; }
#nullable restore
#else
        public string BuildIdRedirectCounter { get; set; }
#endif
        /// <summary>Total history size in bytes, which the workflow might use to decide when to continue-as-new regardless of the suggestion. Note that history event count is just the event id of this event, so we don&apos;t include it explicitly here.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HistorySizeBytes { get; set; }
#nullable restore
#else
        public string HistorySizeBytes { get; set; }
#endif
        /// <summary>Identity of the worker who picked up this task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identity { get; set; }
#nullable restore
#else
        public string Identity { get; set; }
#endif
        /// <summary>This field is populated from the RecordWorkflowTaskStartedRequest. Matching service would set the request_id on the RecordWorkflowTaskStartedRequest to a new UUID. This is useful in case a RecordWorkflowTaskStarted call succeed but matching doesn&apos;t get that response, so matching could retry and history service would return success if the request_id matches. In that case, matching will continue to deliver the task to worker. Without this field, history service would return AlreadyStarted error, and matching would drop the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>The id of the `WORKFLOW_TASK_SCHEDULED` event this task corresponds to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduledEventId { get; set; }
#nullable restore
#else
        public string ScheduledEventId { get; set; }
#endif
        /// <summary>True if this workflow should continue-as-new soon. See `suggest_continue_as_new_reasons` for why.</summary>
        public bool? SuggestContinueAsNew { get; set; }
        /// <summary>The reason(s) that suggest_continue_as_new is true, if it is. Unset if suggest_continue_as_new is false.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes_suggestContinueAsNewReasons?>? SuggestContinueAsNewReasons { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes_suggestContinueAsNewReasons?> SuggestContinueAsNewReasons { get; set; }
#endif
        /// <summary>True if Workflow&apos;s Target Worker Deployment Version is different from its Pinned Version and the workflow is Pinned. Experimental.</summary>
        public bool? TargetWorkerDeploymentVersionChanged { get; set; }
        /// <summary>Version info of the worker to whom this task was dispatched. Deprecated. This field should be cleaned up when versioning-2 API is removed. [cleanup-experimental-wv]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerVersionStamp? WorkerVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.WorkerVersionStamp WorkerVersion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes"/> and sets the default values.
        /// </summary>
        public WorkflowTaskStartedEventAttributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buildIdRedirectCounter", n => { BuildIdRedirectCounter = n.GetStringValue(); } },
                { "historySizeBytes", n => { HistorySizeBytes = n.GetStringValue(); } },
                { "identity", n => { Identity = n.GetStringValue(); } },
                { "requestId", n => { RequestId = n.GetStringValue(); } },
                { "scheduledEventId", n => { ScheduledEventId = n.GetStringValue(); } },
                { "suggestContinueAsNew", n => { SuggestContinueAsNew = n.GetBoolValue(); } },
                { "suggestContinueAsNewReasons", n => { SuggestContinueAsNewReasons = n.GetCollectionOfEnumValues<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes_suggestContinueAsNewReasons>()?.AsList(); } },
                { "targetWorkerDeploymentVersionChanged", n => { TargetWorkerDeploymentVersionChanged = n.GetBoolValue(); } },
                { "workerVersion", n => { WorkerVersion = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerVersionStamp>(global::Soenneker.Temporal.OpenApiClient.Models.WorkerVersionStamp.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("buildIdRedirectCounter", BuildIdRedirectCounter);
            writer.WriteStringValue("historySizeBytes", HistorySizeBytes);
            writer.WriteStringValue("identity", Identity);
            writer.WriteStringValue("requestId", RequestId);
            writer.WriteStringValue("scheduledEventId", ScheduledEventId);
            writer.WriteBoolValue("suggestContinueAsNew", SuggestContinueAsNew);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Temporal.OpenApiClient.Models.WorkflowTaskStartedEventAttributes_suggestContinueAsNewReasons>("suggestContinueAsNewReasons", SuggestContinueAsNewReasons);
            writer.WriteBoolValue("targetWorkerDeploymentVersionChanged", TargetWorkerDeploymentVersionChanged);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.WorkerVersionStamp>("workerVersion", WorkerVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
