// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowExecutionUpdateRejectedEventAttributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cause of rejection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure? Failure { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Failure Failure { get; set; }
#endif
        /// <summary>The instance ID of the update protocol that generated this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProtocolInstanceId { get; set; }
#nullable restore
#else
        public string ProtocolInstanceId { get; set; }
#endif
        /// <summary>The message payload of the original request message that initiated this update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Temporal.OpenApiClient.Models.Request? RejectedRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Temporal.OpenApiClient.Models.Request RejectedRequest { get; set; }
#endif
        /// <summary>The message ID of the original request message that initiated this update. Needed so that the worker can recreate and deliver that same message as part of replay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectedRequestMessageId { get; set; }
#nullable restore
#else
        public string RejectedRequestMessageId { get; set; }
#endif
        /// <summary>The event ID used to sequence the original request message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectedRequestSequencingEventId { get; set; }
#nullable restore
#else
        public string RejectedRequestSequencingEventId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes"/> and sets the default values.
        /// </summary>
        public WorkflowExecutionUpdateRejectedEventAttributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Temporal.OpenApiClient.Models.WorkflowExecutionUpdateRejectedEventAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "failure", n => { Failure = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>(global::Soenneker.Temporal.OpenApiClient.Models.Failure.CreateFromDiscriminatorValue); } },
                { "protocolInstanceId", n => { ProtocolInstanceId = n.GetStringValue(); } },
                { "rejectedRequest", n => { RejectedRequest = n.GetObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Request>(global::Soenneker.Temporal.OpenApiClient.Models.Request.CreateFromDiscriminatorValue); } },
                { "rejectedRequestMessageId", n => { RejectedRequestMessageId = n.GetStringValue(); } },
                { "rejectedRequestSequencingEventId", n => { RejectedRequestSequencingEventId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Failure>("failure", Failure);
            writer.WriteStringValue("protocolInstanceId", ProtocolInstanceId);
            writer.WriteObjectValue<global::Soenneker.Temporal.OpenApiClient.Models.Request>("rejectedRequest", RejectedRequest);
            writer.WriteStringValue("rejectedRequestMessageId", RejectedRequestMessageId);
            writer.WriteStringValue("rejectedRequestSequencingEventId", RejectedRequestSequencingEventId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
