// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Models
{
    /// <summary>Experimental. Optionally decide the versioning behavior that the first task of the new run should use. For example, choose to AutoUpgrade on continue-as-new instead of inheriting the pinned version of the previous run.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowExecutionContinuedAsNewEventAttributes_initialVersioningBehavior
    {
        [EnumMember(Value = "CONTINUE_AS_NEW_VERSIONING_BEHAVIOR_UNSPECIFIED")]
        #pragma warning disable CS1591
        CONTINUE_AS_NEW_VERSIONING_BEHAVIOR_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTINUE_AS_NEW_VERSIONING_BEHAVIOR_AUTO_UPGRADE")]
        #pragma warning disable CS1591
        CONTINUE_AS_NEW_VERSIONING_BEHAVIOR_AUTO_UPGRADE,
        #pragma warning restore CS1591
    }
}
