// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Pause;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Reset;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Unpause;
using Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.UpdateOptions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated
{
    /// <summary>
    /// Builds and executes requests for operations under \namespaces\{namespace}\activities-deprecated
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivitiesDeprecatedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pause property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Pause.PauseRequestBuilder Pause
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Pause.PauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Reset.ResetRequestBuilder Reset
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Reset.ResetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unpause property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Unpause.UnpauseRequestBuilder Unpause
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.Unpause.UnpauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateOptions property</summary>
        public global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.UpdateOptions.UpdateOptionsRequestBuilder UpdateOptions
        {
            get => new global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.UpdateOptions.UpdateOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.ActivitiesDeprecatedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesDeprecatedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/activities-deprecated", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Temporal.OpenApiClient.Namespaces.Item.ActivitiesDeprecated.ActivitiesDeprecatedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesDeprecatedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/namespaces/{namespace}/activities-deprecated", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
