// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Temporal.OpenApiClient.Api.V1.Namespaces.Item.WorkerTaskReachability
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetReachabilityQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TASK_REACHABILITY_UNSPECIFIED")]
        #pragma warning disable CS1591
        TASK_REACHABILITY_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_REACHABILITY_NEW_WORKFLOWS")]
        #pragma warning disable CS1591
        TASK_REACHABILITY_NEW_WORKFLOWS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_REACHABILITY_EXISTING_WORKFLOWS")]
        #pragma warning disable CS1591
        TASK_REACHABILITY_EXISTING_WORKFLOWS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_REACHABILITY_OPEN_WORKFLOWS")]
        #pragma warning disable CS1591
        TASK_REACHABILITY_OPEN_WORKFLOWS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TASK_REACHABILITY_CLOSED_WORKFLOWS")]
        #pragma warning disable CS1591
        TASK_REACHABILITY_CLOSED_WORKFLOWS,
        #pragma warning restore CS1591
    }
}
